# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode='fixed', suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F4FF2BF9580

In [3]:
import pickle

In [4]:
with open("kiwi_experiments.pk", "rb") as file:
    data = pickle.load(file)

In [8]:
list(data)

[439, 445, 449, 468, 474, 475, 482, 484]

In [9]:
for key in data:
    print(key, len(data[key]))

439 24
445 48
449 24
468 24
474 24
475 24
482 24
484 24

In [17]:
for key, val in data[439][15325].items():
    display(val)

,experiment_id,bioreactor_id,container_number,profile_id,starter_culture_id,inactivation_method_id,description_x,color,profile_name,folder_id,...,Acetate_Dilution,Feed_concentration_glc,InducerConcentration,OD_Dilution,Stir_Max_Restarts,pH_correction_factor,ph_Base_conc,ph_Ki,ph_Kp,ph_Tolerance
0,15325,495,9,10068.0,None,1.0,"µ_set: 25%, 0.05 mM IPTG",#FF1B9E77,A2,NaN,...,1,400,500,50,3,0.5,3.5,0.769,15.92,0.1

,cultivation_age,setpoint_id,unit,Feed_glc_cum_setpoints,Flow_Air,InducerConcentration,Puls_AceticAcid,Puls_Glucose,Puls_Medium,StirringSpeed,pH
0,0,661951,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0
1,0,661952,µL,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
2,0,661953,µL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,0,661954,µL,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,1,661955,U/min,NaN,NaN,NaN,NaN,NaN,NaN,2000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
117,50495,665004,µL,2499.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,50795,665005,µL,2533.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,51095,665006,µL,2567.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,51395,665007,µL,2601.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
121,51695,665008,µL,2635.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,measurement_time,measurement_id,unit,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Fluo_GFP,Glucose,OD600,Probe_Volume,pH
0,2020-12-09 09:09:33,21555830,-,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
756,2020-12-09 09:09:33,21555854,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.27
1,2020-12-09 09:09:43,21555878,-,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
757,2020-12-09 09:09:43,21555902,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.27
2,2020-12-09 09:10:19,21555926,-,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
753,2020-12-09 23:31:40,21597679,-,NaN,NaN,NaN,NaN,52.72,NaN,NaN,NaN,NaN,NaN
1510,2020-12-09 23:31:51,21597751,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.44
754,2020-12-09 23:31:51,21597727,-,NaN,NaN,NaN,NaN,52.95,NaN,NaN,NaN,NaN,NaN
1511,2020-12-09 23:32:02,21597799,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.44
755,2020-12-09 23:32:02,21597775,-,NaN,NaN,NaN,NaN,53.24,NaN,NaN,NaN,NaN,NaN

,measurement_time,measurement_id,unit,Flow_Air,Flow_Nitrogen,Flow_O2,StirringSpeed,Temperature
0,2020-12-09 09:09:06,1397494,°C,NaN,NaN,NaN,NaN,36.32
1,2020-12-09 09:09:15,1397495,°C,NaN,NaN,NaN,NaN,36.33
2,2020-12-09 09:09:23,1397496,°C,NaN,NaN,NaN,NaN,36.34
3,2020-12-09 09:09:33,1397497,°C,NaN,NaN,NaN,NaN,36.35
4,2020-12-09 09:10:09,1397498,°C,NaN,NaN,NaN,NaN,36.39
...,...,...,...,...,...,...,...,...
625,2020-12-09 23:31:42,1398116,Ln/min,NaN,NaN,0.0,NaN,NaN
596,2020-12-09 23:32:05,1398120,U/min,NaN,NaN,NaN,0.0,NaN
618,2020-12-09 23:32:05,1398117,Ln/min,NaN,0.0,NaN,NaN,NaN
610,2020-12-09 23:32:05,1398118,Ln/min,0.0,NaN,NaN,NaN,NaN
626,2020-12-09 23:32:05,1398119,Ln/min,NaN,NaN,0.0,NaN,NaN

In [7]:
list(data[439])

[15325,
 15326,
 15327,
 15328,
 15329,
 15330,
 15331,
 15332,
 15333,
 15334,
 15335,
 15336,
 15337,
 15338,
 15339,
 15340,
 15341,
 15342,
 15343,
 15344,
 15345,
 15346,
 15347,
 15348]