# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
from pandas import DataFrame, MultiIndex, Index

rng = np.random.default_rng(0)

valid_range = DataFrame(
    {"start": [1, 2], "stop": [3, 5]}, index=Index(range(2), name="run")
)
midx = MultiIndex(levels=[[], []], codes=[[], []], names=["run", "step"])
data = DataFrame(columns=[f"value{k}" for k in range(3)], index=midx)

for run in range(2):
    for step in range(6):
        data.loc[(run, step), :] = rng.normal(size=(3))

In [9]:
data[[]]

Empty DataFrame
Columns: []
Index: [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (1, 0), (1, 1), (1, 2), (1, 3), (1, 4), (1, 5)]

In [10]:
merged = data[[]].join(valid_range, on="run")
step = merged.index.get_level_values("step")
cond = (merged["start"] <= step) & (step <= merged["stop"])
data[cond]

            value0    value1    value2
run step
0   1       0.1049 -0.535669  0.361595
    2        1.304  0.947081 -0.703735
    3    -1.265421 -0.623274  0.041326
1   2      0.90347  0.094012 -0.743499
    3    -0.921725 -0.457726  0.220195
    4    -1.009618 -0.209176 -0.159225
    5     0.540846  0.214659  0.355373

In [28]:
data.get_level_values(level="step", axis=1)

AttributeError: 'DataFrame' object has no attribute 'get_level_values'

ValueError: MultiIndex has no single backing array. Use 'MultiIndex.to_numpy()' to get a NumPy array of tuples.

In [14]:
data[cond]

/tmp/ipykernel_174103/522956030.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data[cond]

ValueError: cannot reindex from a duplicate axis