# Can we store Tensors on GPU in a DataFrame?

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [24]:
import torch
import numpy as np
import pandas as pd
from pandas import DataFrame

In [6]:
data = torch.randn(100, 100).to(device="cuda")

tensor([[-0.8774, -0.9776,  0.7788,  ...,  0.4452, -1.1846,  0.2122],
        [ 0.4014,  0.6846,  0.8567,  ...,  0.8791,  0.3612, -0.6274],
        [-0.1697, -1.9098, -0.7399,  ...,  0.5694,  0.9103,  0.6339],
        ...,
        [-0.6353,  0.9589,  1.5307,  ..., -0.0179,  0.4928,  0.6722],
        [-2.5971,  0.5789, -1.5088,  ...,  0.8009, -0.2657, -1.3250],
        [-0.4586,  0.4410, -0.6946,  ..., -1.3292,  0.3369, -1.2294]],
       device='cuda:0')

In [7]:
df = DataFrame(data)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,"tensor(-0.8774, device='cuda:0')","tensor(-0.9776, device='cuda:0')","tensor(0.7788, device='cuda:0')","tensor(0.1519, device='cuda:0')","tensor(0.0216, device='cuda:0')","tensor(-0.4200, device='cuda:0')","tensor(0.5566, device='cuda:0')","tensor(1.2260, device='cuda:0')","tensor(2.4237, device='cuda:0')","tensor(0.2887, device='cuda:0')",...,"tensor(-1.8784, device='cuda:0')","tensor(0.8244, device='cuda:0')","tensor(-1.3651, device='cuda:0')","tensor(0.0496, device='cuda:0')","tensor(-1.2043, device='cuda:0')","tensor(0.1488, device='cuda:0')","tensor(0.1644, device='cuda:0')","tensor(0.4452, device='cuda:0')","tensor(-1.1846, device='cuda:0')","tensor(0.2122, device='cuda:0')"
1,"tensor(0.4014, device='cuda:0')","tensor(0.6846, device='cuda:0')","tensor(0.8567, device='cuda:0')","tensor(1.0927, device='cuda:0')","tensor(-0.3680, device='cuda:0')","tensor(0.7945, device='cuda:0')","tensor(0.6330, device='cuda:0')","tensor(-0.1681, device='cuda:0')","tensor(0.1177, device='cuda:0')","tensor(-0.0806, device='cuda:0')",...,"tensor(-1.4677, device='cuda:0')","tensor(1.4655, device='cuda:0')","tensor(-0.3797, device='cuda:0')","tensor(-1.0843, device='cuda:0')","tensor(1.0684, device='cuda:0')","tensor(0.3411, device='cuda:0')","tensor(0.9494, device='cuda:0')","tensor(0.8791, device='cuda:0')","tensor(0.3612, device='cuda:0')","tensor(-0.6274, device='cuda:0')"
2,"tensor(-0.1697, device='cuda:0')","tensor(-1.9098, device='cuda:0')","tensor(-0.7399, device='cuda:0')","tensor(-2.1040, device='cuda:0')","tensor(0.8095, device='cuda:0')","tensor(-0.1696, device='cuda:0')","tensor(0.1575, device='cuda:0')","tensor(-1.1754, device='cuda:0')","tensor(0.8467, device='cuda:0')","tensor(0.3402, device='cuda:0')",...,"tensor(1.6887, device='cuda:0')","tensor(0.7031, device='cuda:0')","tensor(-1.2626, device='cuda:0')","tensor(-0.4395, device='cuda:0')","tensor(1.0362, device='cuda:0')","tensor(-0.8872, device='cuda:0')","tensor(0.8876, device='cuda:0')","tensor(0.5694, device='cuda:0')","tensor(0.9103, device='cuda:0')","tensor(0.6339, device='cuda:0')"
3,"tensor(-0.1156, device='cuda:0')","tensor(0.2290, device='cuda:0')","tensor(1.2611, device='cuda:0')","tensor(-0.1175, device='cuda:0')","tensor(-0.9167, device='cuda:0')","tensor(0.9677, device='cuda:0')","tensor(0.5446, device='cuda:0')","tensor(-0.3116, device='cuda:0')","tensor(-1.5073, device='cuda:0')","tensor(-1.1737, device='cuda:0')",...,"tensor(0.2820, device='cuda:0')","tensor(-0.1586, device='cuda:0')","tensor(0.9044, device='cuda:0')","tensor(-0.7606, device='cuda:0')","tensor(-0.2138, device='cuda:0')","tensor(-1.2940, device='cuda:0')","tensor(-1.0564, device='cuda:0')","tensor(-0.2159, device='cuda:0')","tensor(0.2638, device='cuda:0')","tensor(0.0955, device='cuda:0')"
4,"tensor(-1.0859, device='cuda:0')","tensor(-1.0005, device='cuda:0')","tensor(0.0655, device='cuda:0')","tensor(-0.4895, device='cuda:0')","tensor(0.2016, device='cuda:0')","tensor(0.7391, device='cuda:0')","tensor(1.9562, device='cuda:0')","tensor(1.7338, device='cuda:0')","tensor(-1.3998, device='cuda:0')","tensor(0.5898, device='cuda:0')",...,"tensor(-0.0029, device='cuda:0')","tensor(-1.8574, device='cuda:0')","tensor(0.5356, device='cuda:0')","tensor(0.3696, device='cuda:0')","tensor(0.9479, device='cuda:0')","tensor(0.5947, device='cuda:0')","tensor(0.9860, device='cuda:0')","tensor(0.1988, device='cuda:0')","tensor(-1.1621, device='cuda:0')","tensor(-0.2804, device='cuda:0')"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,"tensor(1.4550, device='cuda:0')","tensor(-0.0765, device='cuda:0')","tensor(0.7049, device='cuda:0')","tensor(1.5714, device='cuda:0')","tensor(0.4101, device='cuda:0')","tensor(0.2183, device='cuda:0')","tensor(-0.5721, device='cuda:0')","tensor(0.1783, device='cuda:0')","tensor(-0.1215, device='cuda:0')","tensor(-1.1612, device='cuda:0')",...,"tensor(-0.4617, device='cuda:0')","tensor(-0.7992, device='cuda:0')","tensor(0.2791, device='cuda:0')","tensor(1.5754, device='cuda:0')","tensor(-1.0759, device='cuda:0')","tensor(-1.1513, device='cuda:0')","tensor(-0.1932, device='cuda:0')","tensor(0.1572, device='cuda:0')","tensor(0.5270, device='cuda:0')","tensor(0.5712, device='cuda:0')"
96,"tensor(1.1575, device='cuda:0')","tensor(0.4229, device='cuda:0')","tensor(0.0177, device='cuda:0')","tensor(0.2945, device='cuda:0')","tensor(0.2328, device='cuda:0')","tensor(-0.4107, device='cuda:0')","tensor(2.1482, device='cuda:0')","tensor(-1.7811, device='cuda:0')","tensor(-0.0592, device='cuda:0')","tensor(-1.2531, device='cuda:0')",...,"tensor(-1.0457, device='cuda:0')","tensor(0.4470, device='cuda:0')","tensor(-2.4364, device='cuda:0')","tensor(0.0802, device='cuda:0')","tensor(-1.2268, device='cuda:0')","tensor(0.1604, device='cuda:0')","tensor(-1.2080, device='cuda:0')","tensor(-0.9732, device='cuda:0')","tensor(1.6407, device='cuda:0')","tensor(-1.7989, device='cuda:0')"
97,"tensor(-0.6353, device='cuda:0')","tensor(0.9589, device='cuda:0')","tensor(1.5307, device='cuda:0')","tensor(-1.3871, device='cuda:0')","tensor(-0.4740, device='cuda:0')","tensor(0.0665, device='cuda:0')","tensor(-0.1613, device='cuda:0')","tensor(0.6918, device='cuda:0')","tensor(0.6242, device='cuda:0')","tensor(-0.3682, device='cuda:0')",...,"tensor(1.1666, device='cuda:0')","tensor(0.7128, device='cuda:0')","tensor(0.0842, device='cuda:0')","tensor(0.3296, device='cuda:0')","tensor(0.3278, device='cuda:0')","tensor(0.5003, device='cuda:0')","tensor(1.5022, device='cuda:0')","tensor(-0.0179, device='cuda:0')","tensor(0.4928, device='cuda:0')","tensor(0.6722, device='cuda:0')"
98,"tensor(-2.5971, device='cuda:0')","tensor(0.5789, device='cuda:0')","tensor(-1.5088, device='cuda:0')","tensor(-0.0717, device='cuda:0')","tensor(-0.7027, device='cuda:0')","tensor(-2.7013, device='cuda:0')","tensor(0.5366, device='cuda:0')","tensor(-0.4278, device='cuda:0')","tensor(0.7245, device='cuda:0')","tensor(0.1596, device='cuda:0')",...,"tensor(-1.6014, device='cuda:0')","tensor(1.9800, device='cuda:0')","tensor(0.2809, device='cuda:0')","tensor(0.0770, device='cuda:0')","tensor(-0.3963, device='cuda:0')","tensor(-0.1933, device='cuda:0')","tensor(-1.7272, device='cuda:0')","tensor(0.8009, device='cuda:0')","tensor(-0.2657, device='cuda:0')","tensor(-1.3250, device='cuda:0')"
99,"tensor(-0.4586, device='cuda:0')","tensor(0.4410, device='cuda:0')","tensor(-0.6946, device='cuda:0')","tensor(0.0976, device='cuda:0')","tensor(0.1044, device='cuda:0')","tensor(1.1240, device='cuda:0')","tensor(-1.4369, device='cuda:0')","tensor(-0.7534, device='cuda:0')","tensor(-0.6973, device='cuda:0')","tensor(-0.6977, device='cuda:0')",...,"tensor(0.3046, device='cuda:0')","tensor(0.8408, device='cuda:0')","tensor(-0.9513, device='cuda:0')","tensor(-0.3753, device='cuda:0')","tensor(0.1775, device='cuda:0')","tensor(0.1182, device='cuda:0')","tensor(-0.2940, device='cuda:0')","tensor(-1.3292, device='cuda:0')","tensor(0.3369, device='cuda:0')","tensor(-1.2294, device='cuda:0')"

In [9]:
%%timeit -n 1 -r 1
data @ data

120 µs ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [10]:
%%timeit -n 1 -r 1
df @ df

9.25 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

# Answer: Yes, but we better not compute with it!

In [27]:
class Wrapper:
    def __init__(self, obj):
        super().__init__()
        self.obj = obj

In [31]:
df = pd.DataFrame(columns=[1])
df[1] = df[1].astype(object)
df.loc[1, 1] = {data}
df

                                                   1
1  {[[tensor(-0.8774, device='cuda:0'), tensor(-0...