# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [2]:
from tsdm.tasks import KIWI_RUNS_TASK
from tsdm.encoders.modular import MinMaxScaler
import numpy as np

INFO:tsdm.config._config:Available Models: {'Informer', 'SET-TS', 'M-RNN', 'IP-Net', 'GRU-ODE-Bayes', 'Latent-ODE', 'NODE', 'ODE-RNN', 'BRITS', 'mTAN', 'NCDE', 'N-BEATS', 'TPA', 'TFT'}
INFO:tsdm.config._config:Available Datasets: {'Traffic', 'Human Activity', 'tourism1', 'M4', 'UWAVE', 'Air Quality', 'Physionet 2019', 'Electricity', 'Character Trajectories', 'Physionet 2012', 'Air Quality Multi-Site', 'Household Consumption', 'tourism2', 'M5', 'MuJoCo', 'USHCN', 'M3'}
INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [3]:
task = KIWI_RUNS_TASK()

KIWI_RUNS_TASK(dataset=KIWI_RUNS, test_metric=RecursiveScriptModule)

In [4]:
task.dataset.timeseries.index.to_frame(index=False)

        run_id  experiment_id    measurement_time
0          439          15325 2020-12-09 09:10:09
1          439          15325 2020-12-09 09:10:19
2          439          15325 2020-12-09 09:10:24
3          439          15325 2020-12-09 09:10:25
4          439          15325 2020-12-09 09:10:34
...        ...            ...                 ...
325947     510          16871 2021-10-26 22:41:26
325948     510          16871 2021-10-26 22:42:11
325949     510          16871 2021-10-26 22:42:20
325950     510          16871 2021-10-26 22:43:22
325951     510          16871 2021-10-26 22:43:31

[325952 rows x 3 columns]

In [9]:
dloader = task.get_dataloader((0, "train"), shuffle=True, batch_size=16)

In [10]:
next(iter(dloader.sampler))

((510, 16869),
 array([261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273,
        274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286,
        287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299,
        300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312,
        313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325,
        326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338,
        339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351,
        352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364,
        365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377,
        378, 379, 380]))

In [11]:
next(iter(dloader))

([Sample(
      key: ((474, 16109), array([  8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,
              21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
              34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,
              47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,
              60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
              73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
              86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
              99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
             112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
             125, 126, 127])),
      inputs: (variable             Flow_Air  StirringSpeed  Temperature  Acetate  Base  \
      measurement_time
      2021-04-20 09:33:51       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:34:55       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:35:14       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:35:58       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:37:01       5.0         2600.0         <NA>     <NA>  <NA>
      ...                       ...            ...          ...      ...   ...
      2021-04-20 10:26:11       5.0            0.0    37.610001     <NA>  <NA>
      2021-04-20 10:26:21       5.0            0.0         <NA>     <NA>  <NA>
      2021-04-20 10:27:22       5.0            0.0    37.630001     <NA>  <NA>
      2021-04-20 10:27:32       5.0            0.0         <NA>     <NA>  <NA>
      2021-04-20 10:28:33       5.0            0.0    37.619999     <NA>  <NA>

      variable             Cumulated_feed_volume_glucose  \
      measurement_time
      2021-04-20 09:33:51                            0.0
      2021-04-20 09:34:55                            0.0
      2021-04-20 09:35:14                            0.0
      2021-04-20 09:35:58                            0.0
      2021-04-20 09:37:01                            0.0
      ...                                            ...
      2021-04-20 10:26:11                            0.0
      2021-04-20 10:26:21                            0.0
      2021-04-20 10:27:22                            0.0
      2021-04-20 10:27:32                            0.0
      2021-04-20 10:28:33                            0.0

      variable             Cumulated_feed_volume_medium        DOT  Glucose  OD600  \
      measurement_time
      2021-04-20 09:33:51                           0.0  83.260002     <NA>   <NA>
      2021-04-20 09:34:55                           0.0  83.260002     <NA>   <NA>
      2021-04-20 09:35:14                       6.18332       <NA>     <NA>   <NA>
      2021-04-20 09:35:58                       6.18332  83.260002     <NA>   <NA>
      2021-04-20 09:37:01                       6.18332  83.260002     <NA>   <NA>
      ...                                           ...        ...      ...    ...
      2021-04-20 10:26:11                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:26:21                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:27:22                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:27:32                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:28:33                    382.578857       <NA>     <NA>   <NA>

      variable             Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
      measurement_time
      2021-04-20 09:33:51           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:34:55           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:35:14           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:35:58           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:37:01           0.0  <NA>      <NA>                   0.0
      ...                           ...   ...       ...                   ...
      2021-04-20 10:26:11         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:26:21         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:27:22         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:27:32         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:28:33         400.0  <NA>      <NA>                   0.0

      variable             Volume
      measurement_time
      2021-04-20 09:33:51    <NA>
      2021-04-20 09:34:55    <NA>
      2021-04-20 09:35:14    <NA>
      2021-04-20 09:35:58    <NA>
      2021-04-20 09:37:01    <NA>
      ...                     ...
      2021-04-20 10:26:11    <NA>
      2021-04-20 10:26:21    <NA>
      2021-04-20 10:27:22    <NA>
      2021-04-20 10:27:32    <NA>
      2021-04-20 10:28:33    <NA>

      [120 rows x 15 columns], Feed_concentration_glc                    200
      OD_Dilution                              20.0
      bioreactor_id                             578
      color                               #FFE7298A
      container_number                           12
      end_time                  2021-04-20 23:08:40
      organism_id                                41
      pH_correction_factor                      0.2
      profile_id                              10800
      profile_name                               D2
      run_name                   20210420_MHE_MPC_3
      start_time                2021-04-20 09:27:23
      Name: (474, 16109), dtype: object),
      targets: variable             Base        DOT  Glucose  OD600
      measurement_time
      2021-04-20 10:15:34  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:15:44  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:16:45  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:16:54  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:17:55  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:18:05  <NA>  99.889999     <NA>   <NA>
      2021-04-20 10:19:06  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:19:16  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:20:09  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:20:17  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:20:27  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:21:28  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:21:38  <NA>      99.82     <NA>   <NA>
      2021-04-20 10:22:39  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:22:48  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:23:50  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:23:59  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:25:00  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:25:10  <NA>  99.919998     <NA>   <NA>
      2021-04-20 10:26:11  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:26:21  <NA>      100.0     <NA>   <NA>
      2021-04-20 10:27:22  <NA>       <NA>     <NA>   <NA>
      2021-04-20 10:27:32  <NA>  99.529999     <NA>   <NA>
      2021-04-20 10:28:33  <NA>       <NA>     <NA>   <NA>,
      originals: (variable             Flow_Air  StirringSpeed  Temperature  Acetate  Base  \
      measurement_time
      2021-04-20 09:33:51       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:34:55       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:35:14       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:35:58       5.0         2600.0         <NA>     <NA>  <NA>
      2021-04-20 09:37:01       5.0         2600.0         <NA>     <NA>  <NA>
      ...                       ...            ...          ...      ...   ...
      2021-04-20 10:26:11       5.0            0.0    37.610001     <NA>  <NA>
      2021-04-20 10:26:21       5.0            0.0         <NA>     <NA>  <NA>
      2021-04-20 10:27:22       5.0            0.0    37.630001     <NA>  <NA>
      2021-04-20 10:27:32       5.0            0.0         <NA>     <NA>  <NA>
      2021-04-20 10:28:33       5.0            0.0    37.619999     <NA>  <NA>

      variable             Cumulated_feed_volume_glucose  \
      measurement_time
      2021-04-20 09:33:51                            0.0
      2021-04-20 09:34:55                            0.0
      2021-04-20 09:35:14                            0.0
      2021-04-20 09:35:58                            0.0
      2021-04-20 09:37:01                            0.0
      ...                                            ...
      2021-04-20 10:26:11                            0.0
      2021-04-20 10:26:21                            0.0
      2021-04-20 10:27:22                            0.0
      2021-04-20 10:27:32                            0.0
      2021-04-20 10:28:33                            0.0

      variable             Cumulated_feed_volume_medium        DOT  Glucose  OD600  \
      measurement_time
      2021-04-20 09:33:51                           0.0  83.260002     <NA>   <NA>
      2021-04-20 09:34:55                           0.0  83.260002     <NA>   <NA>
      2021-04-20 09:35:14                       6.18332       <NA>     <NA>   <NA>
      2021-04-20 09:35:58                       6.18332  83.260002     <NA>   <NA>
      2021-04-20 09:37:01                       6.18332  83.260002     <NA>   <NA>
      ...                                           ...        ...      ...    ...
      2021-04-20 10:26:11                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:26:21                    382.578857      100.0     <NA>   <NA>
      2021-04-20 10:27:22                    382.578857       <NA>     <NA>   <NA>
      2021-04-20 10:27:32                    382.578857  99.529999     <NA>   <NA>
      2021-04-20 10:28:33                    382.578857       <NA>     <NA>   <NA>

      variable             Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
      measurement_time
      2021-04-20 09:33:51           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:34:55           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:35:14           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:35:58           0.0  <NA>      <NA>                   0.0
      2021-04-20 09:37:01           0.0  <NA>      <NA>                   0.0
      ...                           ...   ...       ...                   ...
      2021-04-20 10:26:11         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:26:21         400.0  7.19      <NA>                   0.0
      2021-04-20 10:27:22         400.0  <NA>      <NA>                   0.0
      2021-04-20 10:27:32         400.0   7.2      <NA>                   0.0
      2021-04-20 10:28:33         400.0  <NA>      <NA>                   0.0

      variable             Volume
      measurement_time
      2021-04-20 09:33:51    <NA>
      2021-04-20 09:34:55    <NA>
      2021-04-20 09:35:14    <NA>
      2021-04-20 09:35:58    <NA>
      2021-04-20 09:37:01    <NA>
      ...                     ...
      2021-04-20 10:26:11    <NA>
      2021-04-20 10:26:21    <NA>
      2021-04-20 10:27:22    <NA>
      2021-04-20 10:27:32    <NA>
      2021-04-20 10:28:33    <NA>

      [120 rows x 15 columns], Feed_concentration_glc                    200
      OD_Dilution                              20.0
      bioreactor_id                             578
      color                               #FFE7298A
      container_number                           12
      end_time                  2021-04-20 23:08:40
      organism_id                                41
      pH_correction_factor                      0.2
      profile_id                              10800
      profile_name                               D2
      run_name                   20210420_MHE_MPC_3
      start_time                2021-04-20 09:27:23
      Name: (474, 16109), dtype: object),
  ),
  Sample(
      key: ((468, 15999), array([784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796,
             797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809,
             810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822,
             823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835,
             836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848,
             849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861,
             862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874,
             875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887,
             888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900,
             901, 902, 903])),
      inputs: (variable             Flow_Air  StirringSpeed  Temperature  Acetate  Base  \
      measurement_time
      2021-04-07 17:41:47      10.0            0.0    37.439999     <NA>  <NA>
      2021-04-07 17:41:57      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 17:42:59      10.0            0.0    37.419998     <NA>  <NA>
      2021-04-07 17:43:09      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 17:43:12      10.0            0.0         <NA>     <NA>  <NA>
      ...                       ...            ...          ...      ...   ...
      2021-04-07 18:52:39      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 18:53:41      10.0            0.0    37.509998     <NA>  <NA>
      2021-04-07 18:53:51      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 18:54:53      10.0            0.0    37.529999     <NA>  <NA>
      2021-04-07 18:55:03      10.0            0.0         <NA>     <NA>  <NA>

      variable             Cumulated_feed_volume_glucose  \
      measurement_time
      2021-04-07 17:41:47                          103.0
      2021-04-07 17:41:57                          103.0
      2021-04-07 17:42:59                          103.0
      2021-04-07 17:43:09                          103.0
      2021-04-07 17:43:12                          144.0
      ...                                            ...
      2021-04-07 18:52:39                          150.0
      2021-04-07 18:53:41                          150.0
      2021-04-07 18:53:51                          150.0
      2021-04-07 18:54:53                          150.0
      2021-04-07 18:55:03                          150.0

      variable             Cumulated_feed_volume_medium        DOT  Glucose  OD600  \
      measurement_time
      2021-04-07 17:41:47                   1858.422974       <NA>     <NA>   <NA>
      2021-04-07 17:41:57                   1858.422974  98.230003     <NA>   <NA>
      2021-04-07 17:42:59                   1858.422974       <NA>     <NA>   <NA>
      2021-04-07 17:43:09                   1858.422974  98.650002     <NA>   <NA>
      2021-04-07 17:43:12                   1858.422974       <NA>     <NA>   <NA>
      ...                                           ...        ...      ...    ...
      2021-04-07 18:52:39                     2167.4021       <NA>     <NA>   <NA>
      2021-04-07 18:53:41                     2167.4021       <NA>     <NA>   <NA>
      2021-04-07 18:53:51                     2167.4021       <NA>     <NA>   <NA>
      2021-04-07 18:54:53                     2167.4021       <NA>     <NA>   <NA>
      2021-04-07 18:55:03                     2167.4021       <NA>     <NA>   <NA>

      variable             Probe_Volume    pH  Fluo_GFP  InducerConcentration  \
      measurement_time
      2021-04-07 17:41:47        2000.0  <NA>      <NA>                   0.0
      2021-04-07 17:41:57        2000.0  7.21      <NA>                   0.0
      2021-04-07 17:42:59        2000.0  <NA>      <NA>                   0.0
      2021-04-07 17:43:09        2000.0  7.21      <NA>                   0.0
      2021-04-07 17:43:12        2000.0  <NA>      <NA>                   0.0
      ...                           ...   ...       ...                   ...
      2021-04-07 18:52:39        2400.0  <NA>      <NA>                   2.0
      2021-04-07 18:53:41        2400.0  <NA>      <NA>                   2.0
      2021-04-07 18:53:51        2400.0  <NA>      <NA>                   2.0
      2021-04-07 18:54:53        2400.0  <NA>      <NA>                   2.0
      2021-04-07 18:55:03        2400.0  <NA>      <NA>                   2.0

      variable             Volume
      measurement_time
      2021-04-07 17:41:47    <NA>
      2021-04-07 17:41:57    <NA>
      2021-04-07 17:42:59    <NA>
      2021-04-07 17:43:09    <NA>
      2021-04-07 17:43:12    <NA>
      ...                     ...
      2021-04-07 18:52:39    <NA>
      2021-04-07 18:53:41    <NA>
      2021-04-07 18:53:51    <NA>
      2021-04-07 18:54:53    <NA>
      2021-04-07 18:55:03    <NA>

      [120 rows x 15 columns], Feed_concentration_glc                         200
      OD_Dilution                                   20.0
      bioreactor_id                                  572
      color                                    #FFE6AB02
      container_number                                14
      end_time                       2021-04-07 23:32:05
      organism_id                                     41
      pH_correction_factor                          0.25
      profile_id                                   10690
      profile_name                                    F2
      run_name                  20210407_MHE_MPC_02_real
      start_time                     2021-04-07 09:44:17
      Name: (468, 15999), dtype: object),
      targets: variable             Base        DOT  Glucose  OD600
      measurement_time
      2021-04-07 18:40:40  <NA>  99.489998     <NA>   <NA>
      2021-04-07 18:41:42  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:41:52  <NA>      99.43     <NA>   <NA>
      2021-04-07 18:42:54  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:43:04  <NA>  99.589996     <NA>   <NA>
      2021-04-07 18:44:06  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:44:16  <NA>  99.489998     <NA>   <NA>
      2021-04-07 18:45:18  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:45:28  <NA>  99.620003     <NA>   <NA>
      2021-04-07 18:46:30  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:46:40  <NA>  99.790001     <NA>   <NA>
      2021-04-07 18:47:42  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:47:51  <NA>  99.790001     <NA>   <NA>
      2021-04-07 18:48:54  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:49:03  <NA>  99.940002     <NA>   <NA>
      2021-04-07 18:50:05  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:50:15  <NA>  99.910004     <NA>   <NA>
      2021-04-07 18:51:17  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:51:27  <NA>  99.849998     <NA>   <NA>
      2021-04-07 18:52:39  <NA>  99.910004     <NA>   <NA>
      2021-04-07 18:53:41  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:53:51  <NA>      100.0     <NA>   <NA>
      2021-04-07 18:54:53  <NA>       <NA>     <NA>   <NA>
      2021-04-07 18:55:03  <NA>      100.0     <NA>   <NA>,
      originals: (variable             Flow_Air  StirringSpeed  Temperature  Acetate  Base  \
      measurement_time
      2021-04-07 17:41:47      10.0            0.0    37.439999     <NA>  <NA>
      2021-04-07 17:41:57      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 17:42:59      10.0            0.0    37.419998     <NA>  <NA>
      2021-04-07 17:43:09      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 17:43:12      10.0            0.0         <NA>     <NA>  <NA>
      ...                       ...            ...          ...      ...   ...
      2021-04-07 18:52:39      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 18:53:41      10.0            0.0    37.509998     <NA>  <NA>
      2021-04-07 18:53:51      10.0            0.0         <NA>     <NA>  <NA>
      2021-04-07 18:54:53      10.0            0.0    37.529999     <NA>  <NA>

In [7]:
task.batchloaders

LazyDict(
  (0, 'train'): <LazyFunction: get_dataloader>
  (0, 'test') : <LazyFunction: get_dataloader>
  (1, 'train'): <LazyFunction: get_dataloader>
  (1, 'test') : <LazyFunction: get_dataloader>
  (2, 'train'): <LazyFunction: get_dataloader>
  (2, 'test') : <LazyFunction: get_dataloader>
  (3, 'train'): <LazyFunction: get_dataloader>
  (3, 'test') : <LazyFunction: get_dataloader>
  (4, 'train'): <LazyFunction: get_dataloader>
  (4, 'test') : <LazyFunction: get_dataloader>
)

In [15]:
task.split_idx

split                     0      1      2      3      4
run_id experiment_id
439    15325          train  train  train  train  train
       15326          train  train  train  train  train
       15327          train   test  train  train  train
       15328          train  train   test   test  train
       15329          train  train  train  train  train
...                     ...    ...    ...    ...    ...
510    16867          train  train   test  train  train
       16868          train   test  train  train   test
       16869          train  train  train  train  train
       16870          train   test  train  train   test
       16871          train  train   test  train   test

[216 rows x 5 columns]

In [11]:
dataloader = task.batchloaders[(0, "train")]
dataloader.preprocessor[-1]

TypeError: get_dataloader() missing 1 required positional argument: 'key'

In [ ]:
dataloader = task.batchloaders[(0, "train")]
batch = next(iter(dataloader))

In [ ]:
dataloader.preprocessor.decode(batch)