# KIWI_RUNS Task Object

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import pickle
import pandas
import pandas as pd
import numpy as np
from pandas import DataFrame, Series

pd.set_option("display.max_rows", 10)

In [3]:
import tsdm

ds = tsdm.datasets.KIWI_RUNS

tsdm.datasets.kiwi_runs.KIWI_RUNS

## Stefan's splits

In [4]:
from cross_validate_kiwi_runs import ReplicateBasedSplitter, create_replicate_dict

with open(ds.rawdata_file, "rb") as f:
    experiments_per_run = pickle.load(f)

col_run_to_exp = dict(create_replicate_dict(experiments_per_run))

splitter = ReplicateBasedSplitter()

stefan_splits = []

for train_keys, test_keys in splitter.split(col_run_to_exp):
    stefan_splits.append((train_keys, test_keys))

stefan_splits

[([(474, 16110),
   (474, 16118),
   (474, 16126),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (510, 16855),
   (510, 16863),
   (510, 16871),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (510, 16849),
   (510, 16857),
   (510, 16865),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (510, 16854),
   (510, 16862),
   (510, 16870),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (510, 16850),
   (510, 16858),
   (510, 16866),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (510, 16852),
   (510, 16860),
   (510, 16868),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (474, 16112),
   (474, 16120),
   (474, 16128)],
  [(475, 16133),
   (475, 16141),
   (475, 16149),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (510, 16851),
   (510, 16859),
   (510, 16867),
   (510, 16853),
   (510, 16861),
   (510, 16869),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (510, 16848),
   (510, 16856),
   (510, 16864),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (449, 15647),
   (449, 15655),
   (449, 15663)]),
 ([(445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (510, 16850),
   (510, 16858),
   (510, 16866),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (510, 16852),
   (510, 16860),
   (510, 16868),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (510, 16848),
   (510, 16856),
   (510, 16864),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (510, 16853),
   (510, 16861),
   (510, 16869),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (510, 16855),
   (510, 16863),
   (510, 16871),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (484, 16336),
   (484, 16344),
   (484, 16352)],
  [(468, 15996),
   (468, 16004),
   (468, 16012),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (510, 16854),
   (510, 16862),
   (510, 16870),
   (510, 16849),
   (510, 16857),
   (510, 16865),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (510, 16851),
   (510, 16859),
   (510, 16867),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533)]),
 ([(482, 16283),
   (482, 16291),
   (482, 16299),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (510, 16851),
   (510, 16859),
   (510, 16867),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (510, 16853),
   (510, 16861),
   (510, 16869),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (474, 16109),
   (474, 16117),
   (474, 16125),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (510, 16848),
   (510, 16856),
   (510, 16864),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (510, 16854),
   (510, 16862),
   (510, 16870),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (484, 16332),
   (484, 16340),
   (484, 16348),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (510, 16849),
   (510, 16857),
   (510, 16865),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (484, 16335),
   (484, 16343),
   (484, 16351),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (510, 16855),
   (510, 16863),
   (510, 16871),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (510, 16850),
   (510, 16858),
   (510, 16866)],
  [(475, 16132),
   (475, 16140),
   (475, 16148),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (510, 16852),
   (510, 16860),
   (510, 16868),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (439, 15325),
   (439, 15333),
   (439, 15341)]),
 ([(484, 16335),
   (484, 16343),
   (484, 16351),
   (482, 16283),
   (482, 16291),
   (482, 16299),
   (510, 16854),
   (510, 16862),
   (510, 16870),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (510, 16852),
   (510, 16860),
   (510, 16868),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (468, 15996),
   (468, 16004),
   (468, 16012),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (510, 16849),
   (510, 16857),
   (510, 16865),
   (475, 16137),
   (475, 16145),
   (475, 16153),
   (355, 11724),
   (355, 11732),
   (355, 11740),
   (445, 15497),
   (445, 15505),
   (445, 15513),
   (445, 15515),
   (445, 15521),
   (445, 15523),
   (445, 15529),
   (445, 15537),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (475, 16133),
   (475, 16141),
   (475, 16149),
   (445, 15495),
   (445, 15503),
   (445, 15507),
   (445, 15511),
   (445, 15519),
   (445, 15527),
   (445, 15535),
   (445, 15539),
   (482, 16288),
   (482, 16296),
   (482, 16304),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (475, 16131),
   (475, 16139),
   (475, 16147),
   (484, 16334),
   (484, 16342),
   (484, 16350),
   (510, 16850),
   (510, 16858),
   (510, 16866),
   (449, 15646),
   (449, 15654),
   (449, 15662),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (482, 16286),
   (482, 16294),
   (482, 16302),
   (484, 16336),
   (484, 16344),
   (484, 16352),
   (468, 15999),
   (468, 16007),
   (468, 16015),
   (475, 16132),
   (475, 16140),
   (475, 16148),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (439, 15325),
   (439, 15333),
   (439, 15341),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (468, 16000),
   (468, 16008),
   (468, 16016),
   (474, 16108),
   (474, 16116),
   (474, 16124),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (468, 15997),
   (468, 16005),
   (468, 16013),
   (449, 15645),
   (449, 15653),
   (449, 15661),
   (484, 16331),
   (484, 16339),
   (484, 16347),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (474, 16112),
   (474, 16120),
   (474, 16128),
   (482, 16289),
   (482, 16297),
   (482, 16305),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (474, 16113),
   (474, 16121),
   (474, 16129),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (468, 15995),
   (468, 16003),
   (468, 16011),
   (510, 16853),
   (510, 16861),
   (510, 16869),
   (475, 16134),
   (475, 16142),
   (475, 16150),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (474, 16109),
   (474, 16117),
   (474, 16125)],
  [(484, 16332),
   (484, 16340),
   (484, 16348),
   (474, 16110),
   (474, 16118),
   (474, 16126),
   (355, 11726),
   (355, 11734),
   (355, 11742),
   (445, 15496),
   (445, 15504),
   (445, 15508),
   (445, 15512),
   (445, 15516),
   (445, 15520),
   (445, 15528),
   (445, 15536),
   (474, 16111),
   (474, 16119),
   (474, 16127),
   (468, 16001),
   (468, 16009),
   (468, 16017),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (475, 16135),
   (475, 16143),
   (475, 16151),
   (510, 16851),
   (510, 16859),
   (510, 16867),
   (482, 16284),
   (482, 16292),
   (482, 16300),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (449, 15649),
   (449, 15657),
   (449, 15665),
   (475, 16136),
   (475, 16144),
   (475, 16152),
   (510, 16855),
   (510, 16863),
   (510, 16871),
   (439, 15331),
   (439, 15339),
   (439, 15347),
   (439, 15330),
   (439, 15338),
   (439, 15346),
   (510, 16848),
   (510, 16856),
   (510, 16864),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (449, 15643),
   (449, 15651),
   (449, 15659),
   (355, 11728),
   (355, 11736),
   (355, 11744)]),
 ([(475, 16134),
   (475, 16142),
   (475, 16150),
   (439, 15329),
   (439, 15337),
   (439, 15345),
   (439, 15326),
   (439, 15334),
   (439, 15342),
   (449, 15650),
   (449, 15658),
   (449, 15666),
   (445, 15494),
   (445, 15502),
   (445, 15510),
   (445, 15518),
   (445, 15524),
   (445, 15526),
   (445, 15534),
   (445, 15540),
   (355, 11725),
   (355, 11733),
   (355, 11741),
   (474, 16106),
   (474, 16114),
   (474, 16122),
   (445, 15493),
   (445, 15499),
   (445, 15501),
   (445, 15509),
   (445, 15517),
   (445, 15525),
   (445, 15531),
   (445, 15533),
   (445, 15498),
   (445, 15500),
   (445, 15506),
   (445, 15514),
   (445, 15522),
   (445, 15530),
   (445, 15532),
   (445, 15538),
   (484, 16330),
   (484, 16338),
   (484, 16346),
   (355, 11728),
   (355, 11736),
   (355, 11744),
   (355, 11723),
   (355, 11731),
   (355, 11739),
   (449, 15644),
   (449, 15652),
   (449, 15660),
   (484, 16333),
   (484, 16341),
   (484, 16349),
   (468, 15994),
   (468, 16002),
   (468, 16010),
   (468, 15998),
   (468, 16006),
   (468, 16014),
   (482, 16285),
   (482, 16293),
   (482, 16301),
   (482, 16282),
   (482, 16290),
   (482, 16298),
   (449, 15648),
   (449, 15656),
   (449, 15664),
   (439, 15327),
   (439, 15335),
   (439, 15343),
   (449, 15647),
   (449, 15655),
   (449, 15663),
   (482, 16287),
   (482, 16295),
   (482, 16303),
   (474, 16107),
   (474, 16115),
   (474, 16123),
   (510, 16850),
   (510, 16858),
   (510, 16866),
   (439, 15328),
   (439, 15336),
   (439, 15344),
   (475, 16130),
   (475, 16138),
   (475, 16146),
   (439, 15332),
   (439, 15340),
   (439, 15348),
   (510, 16852),
   (510, 16860),
   (510, 16868),
   (355, 11722),
   (355, 11730),
   (355, 11738),
   (355, 11727),
   (355, 11735),
   (355, 11743),
   (484, 16337),
   (484, 16345),
   (484, 16353),
   (510, 16851),
   (510, 16859),
   (510, 16867),
   (355, 11729),
   (355, 11737),
   (355, 11745),
   (510, 16848),
   (510, 16856),
   (510, 16864),
   (468, 15999),
   (468, 16007),

In [5]:
from tsdm.datasets import KIWI_RUNS

metadata = KIWI_RUNS.metadata
timeseries = KIWI_RUNS.dataset

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12      <NA>           <NA>
                     2019-04-09 18:32:18      <NA>           <NA>
                     2019-04-09 18:32:19      <NA>           <NA>
                     2019-04-09 18:32:21  4.997213           <NA>
                     2019-04-09 18:32:22      <NA>           <NA>
...                                            ...            ...
510    16871         2021-10-26 22:41:26      <NA>           <NA>
                     2021-10-26 22:42:11      <NA>           <NA>
                     2021-10-26 22:42:20      <NA>           <NA>
                     2021-10-26 22:43:22      <NA>           <NA>
                     2021-10-26 22:43:31      <NA>           <NA>

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26         <NA>     <NA>  <NA>
                     2021-10-26 22:42:11    37.450001     <NA>  <NA>
                     2021-10-26 22:42:20         <NA>     <NA>  <NA>
                     2021-10-26 22:43:22    37.439999     <NA>  <NA>
                     2021-10-26 22:43:31         <NA>     <NA>  <NA>

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           <NA>
                     2019-04-09 18:32:18                           <NA>
                     2019-04-09 18:32:19                           <NA>
                     2019-04-09 18:32:21                           <NA>
                     2019-04-09 18:32:22                           <NA>
...                                                                 ...
510    16871         2021-10-26 22:41:26                           <NA>
                     2021-10-26 22:42:11                           <NA>
                     2021-10-26 22:42:20                           <NA>
                     2021-10-26 22:43:22                           <NA>
                     2021-10-26 22:43:31                           <NA>

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
510    16871         2021-10-26 22:41:26                          <NA>
                     2021-10-26 22:42:11                          <NA>
                     2021-10-26 22:42:20                          <NA>
                     2021-10-26 22:43:22                          <NA>
                     2021-10-26 22:43:31                          <NA>

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26       <NA>     <NA>   <NA>
                     2021-10-26 22:42:11       <NA>     <NA>   <NA>
                     2021-10-26 22:42:20  79.459999     <NA>   <NA>
                     2021-10-26 22:43:22       <NA>     <NA>   <NA>
                     2021-10-26 22:43:31  78.860001     <NA>   <NA>

                                          Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12          <NA>      <NA>      <NA>
                     2019-04-09 18:32:18          <NA>      <NA>      <NA>
                     2019-04-09 18:32:19          <NA>      6.86      <NA>
                     2019-04-09 18:32:21          <NA>      <NA>      <NA>
                     2019-04-09 18:32:22          <NA>      <NA>      <NA>
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26          <NA>      <NA>      <NA>
                     2021-10-26 22:42:11          <NA>      <NA>      <NA>
                     2021-10-26 22:42:20          <NA>  7.320229      <NA>
                     2021-10-26 22:43:22          <NA>      <NA>      <NA>
                     2021-10-26 22:43:31          <NA>  7.336412      <NA>

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                  <NA>    <NA>
                     2019-04-09 18:32:18                  <NA>    <NA>
                     2019-04-09 18:32:19                  <NA>    <NA>
                     2019-04-09 18:32:21                  <NA>    <NA>
                     2019-04-09 18:32:22                  <NA>    <NA>
...                                                        ...     ...
510    16871         2021-10-26 22:41:26                  <NA>     0.0
                     2021-10-26 22:42:11                  <NA>    <NA>
                     2021-10-26 22:42:20                  <NA>    <NA>
                     2021-10-26 22:43:22                  <NA>    <NA>
                     2021-10-26 22:43:31                  <NA>    <NA>

[441907 rows x 15 columns]

In [6]:
reverse_lookup = {}

for run_id in metadata.index.unique("run_id"):
    colors = metadata["color"][[run_id]]
    for color in colors.unique():
        mask = colors == color
        indices = colors[colors == color].index.tolist()
        reverse_lookup[(color, run_id)] = indices

assert reverse_lookup == col_run_to_exp

## groupby solution

https://stackoverflow.com/a/51329888/9318372

In [7]:
rev = metadata.groupby(["color", "run_id"]).groups
rev = {key: idx.tolist() for key, idx in rev.items()}
assert rev == col_run_to_exp

## Custom splitting logic

In [8]:
from sklearn.model_selection import ShuffleSplit
from itertools import chain

splitter = ShuffleSplit(n_splits=5, random_state=0, test_size=0.25)
groups = metadata.groupby(["color", "run_id"])
rev_idx = groups.ngroup()
groups = metadata.groupby(["color", "run_id"])
group_idx = groups.ngroup()

splits = DataFrame(index=metadata.index)
for i, (train, test) in enumerate(splitter.split(groups)):
    splits[i] = group_idx.isin(train).map({False: "test", True: "train"})

splits.columns.name = "split"
splits.astype("string").astype("category")

split                     0      1      2      3      4
run_id experiment_id
355    11722          train   test  train  train   test
       11723          train  train  train   test   test
       11724          train  train  train  train  train
       11725           test  train   test  train   test
       11726          train  train  train  train  train
...                     ...    ...    ...    ...    ...
510    16867           test   test  train   test  train
       16868          train   test   test   test  train
       16869          train  train   test   test  train
       16870           test   test   test  train   test
       16871          train  train   test  train  train

[264 rows x 5 columns]

## Loss function

Divide 'Glucose' by 10, 'OD600' by 20, 'DOT' by 100, 'Base' by 200, then use RMSE.

In [9]:
targets = {"Glucose", "OD600", "DOT", "Base"}
assert targets <= set(timeseries.columns)

In [10]:
timeseries.min()

Flow_Air                  0.000000
StirringSpeed             0.000000
Temperature              32.689999
Acetate                   0.000000
Base                      0.000000
                           ...
Probe_Volume            200.000000
pH                        0.000000
Fluo_GFP                  0.000000
InducerConcentration      0.000000
Volume                    0.000000
Length: 15, dtype: float32

In [11]:
timeseries.max()

Flow_Air                    10.000000
StirringSpeed             2600.000000
Temperature                 41.380001
Acetate                      1.183919
Base                      4070.000000
                            ...
Probe_Volume              5550.000000
pH                           8.600000
Fluo_GFP                586421.875000
InducerConcentration         2.000000
Volume                    2551.117188
Length: 15, dtype: float32

In [12]:
timeseries.max() - timeseries.min()

Flow_Air                    10.000000
StirringSpeed             2600.000000
Temperature                  8.690002
Acetate                      1.183919
Base                      4070.000000
                            ...
Probe_Volume              5350.000000
pH                           8.600000
Fluo_GFP                586421.875000
InducerConcentration         2.000000
Volume                    2551.117188
Length: 15, dtype: float32

In [13]:
from itertools import product

In [14]:
list(product(range(5), ("train", "test")))

[(0, 'train'),
 (0, 'test'),
 (1, 'train'),
 (1, 'test'),
 (2, 'train'),
 (2, 'test'),
 (3, 'train'),
 (3, 'test'),
 (4, 'train'),
 (4, 'test')]

In [15]:
timeseries.dtypes

Flow_Air                Float32
StirringSpeed           Float32
Temperature             Float32
Acetate                 Float32
Base                    Float32
                         ...
Probe_Volume            Float32
pH                      Float32
Fluo_GFP                Float32
InducerConcentration    Float32
Volume                  Float32
Length: 15, dtype: object

In [16]:
mask = splits[0] == "train"
idx = splits[0][mask].index

MultiIndex([(355, 11722),
            (355, 11723),
            (355, 11724),
            (355, 11726),
            (355, 11727),
            (355, 11729),
            (355, 11730),
            (355, 11731),
            (355, 11732),
            (355, 11734),
            ...
            (510, 16858),
            (510, 16860),
            (510, 16861),
            (510, 16863),
            (510, 16864),
            (510, 16865),
            (510, 16866),
            (510, 16868),
            (510, 16869),
            (510, 16871)],
           names=['run_id', 'experiment_id'], length=189)

In [17]:
timeseries.reset_index(level=2).loc[idx].set_index(["measurement_time"], append=True)

                                          Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12      <NA>           <NA>
                     2019-04-09 18:32:18      <NA>           <NA>
                     2019-04-09 18:32:19      <NA>           <NA>
                     2019-04-09 18:32:21  4.997213           <NA>
                     2019-04-09 18:32:22      <NA>           <NA>
...                                            ...            ...
510    16871         2021-10-26 22:41:26      <NA>           <NA>
                     2021-10-26 22:42:11      <NA>           <NA>
                     2021-10-26 22:42:20      <NA>           <NA>
                     2021-10-26 22:43:22      <NA>           <NA>
                     2021-10-26 22:43:31      <NA>           <NA>

                                          Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26         <NA>     <NA>  <NA>
                     2021-10-26 22:42:11    37.450001     <NA>  <NA>
                     2021-10-26 22:42:20         <NA>     <NA>  <NA>
                     2021-10-26 22:43:22    37.439999     <NA>  <NA>
                     2021-10-26 22:43:31         <NA>     <NA>  <NA>

                                          Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           <NA>
                     2019-04-09 18:32:18                           <NA>
                     2019-04-09 18:32:19                           <NA>
                     2019-04-09 18:32:21                           <NA>
                     2019-04-09 18:32:22                           <NA>
...                                                                 ...
510    16871         2021-10-26 22:41:26                           <NA>
                     2021-10-26 22:42:11                           <NA>
                     2021-10-26 22:42:20                           <NA>
                     2021-10-26 22:43:22                           <NA>
                     2021-10-26 22:43:31                           <NA>

                                          Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                          <NA>
                     2019-04-09 18:32:18                          <NA>
                     2019-04-09 18:32:19                          <NA>
                     2019-04-09 18:32:21                          <NA>
                     2019-04-09 18:32:22                          <NA>
...                                                                ...
510    16871         2021-10-26 22:41:26                          <NA>
                     2021-10-26 22:42:11                          <NA>
                     2021-10-26 22:42:20                          <NA>
                     2021-10-26 22:43:22                          <NA>
                     2021-10-26 22:43:31                          <NA>

                                                DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26       <NA>     <NA>   <NA>
                     2021-10-26 22:42:11       <NA>     <NA>   <NA>
                     2021-10-26 22:42:20  79.459999     <NA>   <NA>
                     2021-10-26 22:43:22       <NA>     <NA>   <NA>
                     2021-10-26 22:43:31  78.860001     <NA>   <NA>

                                          Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12          <NA>      <NA>      <NA>
                     2019-04-09 18:32:18          <NA>      <NA>      <NA>
                     2019-04-09 18:32:19          <NA>      6.86      <NA>
                     2019-04-09 18:32:21          <NA>      <NA>      <NA>
                     2019-04-09 18:32:22          <NA>      <NA>      <NA>
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26          <NA>      <NA>      <NA>
                     2021-10-26 22:42:11          <NA>      <NA>      <NA>
                     2021-10-26 22:42:20          <NA>  7.320229      <NA>
                     2021-10-26 22:43:22          <NA>      <NA>      <NA>
                     2021-10-26 22:43:31          <NA>  7.336412      <NA>

                                          InducerConcentration  Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                  <NA>    <NA>
                     2019-04-09 18:32:18                  <NA>    <NA>
                     2019-04-09 18:32:19                  <NA>    <NA>
                     2019-04-09 18:32:21                  <NA>    <NA>
                     2019-04-09 18:32:22                  <NA>    <NA>
...                                                        ...     ...
510    16871         2021-10-26 22:41:26                  <NA>     0.0
                     2021-10-26 22:42:11                  <NA>    <NA>
                     2021-10-26 22:42:20                  <NA>    <NA>
                     2021-10-26 22:43:22                  <NA>    <NA>
                     2021-10-26 22:43:31                  <NA>    <NA>

[326927 rows x 15 columns]

# Implementation

In [18]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

## Splits

In [19]:
from tsdm.tasks import KIWI_RUNS_TASK

TASK = KIWI_RUNS_TASK()

In [20]:
TASK.splits((4, "train"))[0]

KeyError: 'color'

## Preprocessing

### Encoding the metadata

```
Feed_concentration_glc             Int16 → convert to float
OD_Dilution                      Float32 → keep as-is
bioreactor_id                     UInt32 → drop / One-Hot
color                           category → drop / One-Hot
container_number                  UInt32 → drop
end_time                  datetime64[ns] → drop, but use for time-scaling
organism_id                       UInt32 → One-Hot
pH_correction_factor             Float32 → keep as-is
profile_id                        UInt32 → drop
profile_name                    category → drop
run_name                        category → drop
start_time                datetime64[ns] → drop, but use for time-scaling
```

In [ ]:
ts = KIWI_RUNS.dataset
md = KIWI_RUNS.metadata

### Consistency check: are the observation timestamps within start_time and end_time reported in metadata?

In [ ]:
from tsdm.datasets import KIWI_RUNS
from tqdm.auto import tqdm

KIWI_RUNS.clean()

In [ ]:
ts = KIWI_RUNS.dataset
ts

In [ ]:
md = KIWI_RUNS.metadata
md
# ts = ts.reset_index(level="measurement_time")
# pandas.testing.assert_index_equal(md.index, ts.index.unique())

In [ ]:
md.index.get_level_values([0, 1])

In [ ]:
ts.drop(355)

In [ ]:
merged = ts[[]].join(md[["start_time", "end_time"]])
time = merged.index.get_level_values("measurement_time")
cond = (merged["start_time"] <= time) & (time <= merged["end_time"])
ts[cond]

In [ ]:
data[cond]

In [ ]:
times = ts.reset_index()[["run_id", "experiment_id", "measurement_time"]]

In [ ]:
times = ts.reset_index(level=2)[["measurement_time"]]

In [ ]:
times

In [ ]:
times = times.merge(start_stop, how="left", on=["run_id", "experiment_id"])

In [ ]:
cond = (times["start_time"] <= times["measurement_time"]) & (
    times["measurement_time"] <= times["end_time"]
)

In [ ]:
times[cond]

In [ ]:
ts[cond.values]

In [ ]:
for idx, group in ts.groupby(level=[0, 1]):
    valid_times = (md.loc[idx, "start_time"] <= ts.loc[idx].index) & (
        ts.loc[idx].index <= md.loc[idx, "end_time"]
    )
    ...

In [ ]:
group.apply(lambda x: x[~valid_times])

In [ ]:
group.app

In [ ]:
for idx in tqdm(md.index):
    valid_times = (md.loc[idx, "start_time"] <= ts.loc[idx].index) & (
        ts.loc[idx].index <= md.loc[idx, "end_time"]
    )
    valid_index = ts.loc[idx].loc[valid_times].index
    # ts = ts.drop(valid_index)
    break

In [ ]:
len(ts)

In [ ]:
ts.loc[idx]

In [ ]:
ts.loc[idx] = ts.loc[idx].drop(valid_index)

In [ ]:
ts.loc[idx]

In [ ]:
ts.drop()

In [ ]:
for idx in tqdm(md.index):
    valid_times = (md.loc[idx, "start_time"] <= ts.loc[idx].index) & (
        ts.loc[idx].index <= md.loc[idx, "end_time"]
    )
    valid_index = ts.loc[idx].loc[valid_times].index
    # ts = ts.drop(valid_index)

In [ ]:
len(ts)

In [ ]:
valid_times

In [ ]:
ts.loc[idx] = ts.loc[idx].loc[valid_times]

In [ ]:
ts.loc[idx].loc[valid_times]

In [ ]:
ts.loc[idx]["measurement_time"]

In [ ]:
first_obs = ts["measurement_time"].groupby(["run_id", "experiment_id"]).min()

In [ ]:
# ts = ts.reset_index(level=2)
runs = ts.index.get_level_values("run_id").unique()

times = DataFrame(
    index=md.index, columns=["ts_start", "ts_final", "md_start", "md_final"]
)

for idx in md.index:
    ts_slice = ts.loc[idx]
    md_slice = md.loc[idx]
    times.loc[idx, "ts_start"] = ts.loc[idx, "measurement_time"].min()
    times.loc[idx, "ts_final"] = ts.loc[idx, "measurement_time"].max()
    times.loc[idx, "md_start"] = md.loc[idx, "start_time"]
    times.loc[idx, "md_final"] = md.loc[idx, "end_time"]

times

In [ ]:
discr = DataFrame()
discr["MD₀-TS₀"] = times["md_start"] - times["ts_start"]
discr["MDₜ-TSₜ"] = times["md_final"] - times["ts_final"]
discr = discr / np.timedelta64(1, "s")
discr = discr.groupby("run_id").mean()
with pd.option_context("display.float_format", "{:.0f}".format):
    display(discr)

## What went wrong?

In [ ]:
import matplotlib.pyplot as plt

times.loc[475, 16130]

In [ ]:
exp = ts.loc[475, 16130]

In [ ]:
pandas.isna(exp).mean()

In [ ]:
T = exp["measurement_time"]
T = T - T.iloc[0]
DOT = exp["DOT"].astype(float).values
PH = exp["pH"].astype(float).values
TEMP = exp["Temperature"].astype(float).values

In [ ]:
exp.set_index("measurement_time")

In [ ]:
slc.iloc[-1]

In [ ]:
slc = exp.set_index("measurement_time").loc[:"2021-06-01"]
pandas.isna(slc).mean()

In [ ]:
fig, ax = plt.subplots(figsize=(10, 4))
ax.plot(T, DOT, T, PH, T, TEMP)
ax.legend(["DOT", "pH", "Temp"])

In [ ]:
DataFrame.from_dict(start_times, orient=)

In [ ]:
metadata["start_time"]

In [ ]:
md = metadata.drop(355)
assert not pandas.isna(md).any(axis=None), "DataFrame contains NANs!!"

In [ ]:
drop_vals = [
    "bioreactor_id",
    "color",
    "container_number",
    "end_time",
    "start_time",
    "profile_id",
    "profile_name",
    "run_name",
    "organism_id",
]

In [ ]:
md = md.drop(columns=drop_vals).astype("Float32")

In [ ]:
md["Feed_concentration_glc"] = md["Feed_concentration_glc"].astype("Float32")

In [ ]:
md["organism_id"] = md["organism_id"].astype("category")

In [ ]:
pandas.get_dummies(md, columns=["organism_id"])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
preprocessor = StandardScaler()
ts, md = TASK.splits((4, "train"))

In [ ]:
preprocessor.fit(ts)
preprocessor.transform(ts, copy=False)
ts

## Encoding in torch

In [ ]:
import torch
from tsdm.encoders.functional import time2float

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.float32
ts = ts.reset_index(level=2)  # make measurements regular col

In [ ]:
time2float(ts["measurement_time"].values)

In [ ]:
T = torch.tensor(time2float(ts["measurement_time"].values), device=device, dtype=dtype)
X = torch.tensor(
    ts.drop(columns=["measurement_time"]).values, device=device, dtype=dtype
)

## Creating DataSetCollection Object

In [ ]:
from tsdm.datasets import DataSetCollection
from torch.utils.data import TensorDataset

In [ ]:
shared_index = ts.index.unique().values
masks = {idx: (ts.index == idx) for idx in shared_index}
datasets = {idx: TensorDataset(T[masks[idx]], X[masks[idx]]) for idx in shared_index}

In [ ]:
from pandas import Series

In [ ]:
s = Series(datasets)

In [ ]:
dataset = DataSetCollection(datasets)

In [ ]:
some_index = ts.index.values[42]
dataset[some_index]

In [ ]:
dataset[some_index][:10]

## Creating CollectionSampler Object

In [ ]:
from tsdm.util.samplers import CollectionSampler, SequenceSampler
from torch.utils.data import TensorDataset
from functools import partial

subsampler = partial(SequenceSampler, seq_len=100, shuffle=True)
sampler = CollectionSampler(dataset, subsampler=subsampler)

In [ ]:
sample = next(iter(sampler))
element = dataset[sample]

In [ ]:
from tqdm.auto import tqdm

for b in tqdm(sampler):
    ...

## DataLoader Object

In [ ]:
from torch.utils.data import DataLoader

In [ ]:
dloader = DataLoader(dataset, sampler=sampler, batch_size=32)

In [ ]:
next(iter(dloader))

In [ ]:
for batch in tqdm(dloader):
    ...

## Testing implemented variant

In [ ]:
from tsdm.tasks import KIWI_RUNS_TASK

task = KIWI_RUNS_TASK()

In [ ]:
task.dataloaders

In [ ]:
dloader = task.batchloader[0]

In [ ]:
T, X = next(iter(dloader))

In [ ]:
T.shape, X.shape

In [ ]:
for batch in tqdm(dloader):
    ...

In [ ]:
for batch in tqdm(task.dataloaders[(0, "train")]):
    ...