# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
import tsdm
dset =  tsdm.datasets.USHCN_SmallChunkedSporadic
ds = tsdm.datasets.USHCN_SmallChunkedSporadic.dataset

,ID,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
0,0,180.3,-0.3057,0.0,0.0,0.0,0.000000,True,False,False,False,False
1,0,168.6,-0.3057,0.0,0.0,0.0,0.000000,True,False,False,False,False
2,0,31.4,-0.3057,0.0,0.0,0.0,0.000000,True,False,False,False,False
3,0,5.9,-0.3057,0.0,0.0,0.0,0.000000,True,False,False,False,False
4,0,32.6,-0.3057,0.0,0.0,0.0,0.000000,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
350660,1122,180.1,0.0000,0.0,0.0,0.0,0.719049,False,False,False,False,True
350661,1122,84.8,0.0000,0.0,0.0,0.0,0.197300,False,False,False,False,True
350662,1122,160.0,0.0000,0.0,0.0,0.0,-1.002722,False,False,False,False,True
350663,1122,25.8,0.0000,0.0,0.0,0.0,0.145125,False,False,False,False,True
350664,1122,156.9,0.0000,0.0,0.0,0.0,-1.263596,False,False,False,False,True

In [4]:
from tsdm.util import Split

In [5]:
N = ds["ID"].nunique()

num_folds = 5
np.random.seed(432)

folds = []
for fold in range(num_folds):
    train_idx, test_idx = train_test_split(np.arange(N), test_size=0.1)
    train_idx, val_idx = train_test_split(train_idx, test_size=0.2)
    folds.append(Split(train=train_idx, valid=val_idx, test=test_idx))

In [6]:
import gru_ode_bayes
from gru_ode_bayes.data_utils import ODE_Dataset

In [7]:
el = ODE_Dataset(panda_df = ds, idx=folds[0].train )[0]
print(el.keys())

dict_keys(['idx', 'y', 'path', 'cov', 'val_samples', 'store_last'])

In [8]:
el["path"]

,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
ID,,,,,,,,,,,
0,0.300000,0.0,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0
0,0.600000,0.0,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0
0,0.700000,0.0,0.00000,0.000000,0.000000,0.614699,0.0,0.0,0.0,0.0,1.0
0,1.500000,0.0,0.00000,0.000000,0.000000,0.823399,0.0,0.0,0.0,0.0,1.0
0,1.900000,0.0,0.00000,0.000000,0.318966,0.000000,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
0,198.899994,0.0,0.00000,0.000000,-0.970004,0.000000,0.0,0.0,0.0,1.0,0.0
0,199.300003,0.0,0.00000,0.000000,-0.206170,0.000000,0.0,0.0,0.0,1.0,0.0
0,199.500000,0.0,0.00000,-0.173762,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0
0,199.699997,0.0,0.00000,0.000000,0.000000,-0.533148,0.0,0.0,0.0,0.0,1.0
0,199.899994,0.0,0.00000,0.000000,0.000000,-0.794022,0.0,0.0,0.0,0.0,1.0

In [9]:
ds.loc[ds["ID"]==0].sort_values("Time")

,ID,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
155,0,0.4,0.0000,0.0,-0.173762,0.000000,0.000000,False,False,True,False,False
205,0,0.6,0.0000,0.0,0.000000,0.128008,0.000000,False,False,False,True,False
171,0,1.2,0.0000,0.0,-0.173762,0.000000,-0.480973,False,False,True,False,True
55,0,1.4,-0.3057,0.0,0.000000,0.000000,0.000000,True,False,False,False,False
257,0,2.3,0.0000,0.0,0.000000,0.000000,-1.002722,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
232,0,198.7,0.0000,0.0,0.000000,-0.588087,0.000000,False,False,False,True,False
172,0,198.8,0.0000,0.0,-0.173762,0.000000,0.000000,False,False,True,False,False
248,0,199.2,0.0000,0.0,0.000000,0.000000,-0.846197,False,False,False,False,True
234,0,199.9,0.0000,0.0,0.000000,-0.826785,0.000000,False,False,False,True,False
211,0,200.0,0.0000,0.0,0.000000,-1.351921,0.000000,False,False,False,True,False