# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [3]:
import tsdm
USHCN =  tsdm.datasets.USHCN_SmallChunkedSporadic
ds = USHCN.dataset

,ID,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
0,0,180.300003,-0.3057,0.0,0.0,0.0,0.0,True,False,False,False,False
1,0,168.600006,-0.3057,0.0,0.0,0.0,0.0,True,False,False,False,False
2,0,31.4,-0.3057,0.0,0.0,0.0,0.0,True,False,False,False,False
3,0,5.9,-0.3057,0.0,0.0,0.0,0.0,True,False,False,False,False
4,0,32.599998,-0.3057,0.0,0.0,0.0,0.0,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
350660,1122,180.100006,0.0,0.0,0.0,0.0,0.719049,False,False,False,False,True
350661,1122,84.800003,0.0,0.0,0.0,0.0,0.1973,False,False,False,False,True
350662,1122,160.0,0.0,0.0,0.0,0.0,-1.002722,False,False,False,False,True
350663,1122,25.799999,0.0,0.0,0.0,0.0,0.145125,False,False,False,False,True
350664,1122,156.899994,0.0,0.0,0.0,0.0,-1.263596,False,False,False,False,True

In [4]:
from tsdm.util import Split
N = ds["ID"].nunique()

num_folds = 5
np.random.seed(432)

folds = []
for fold in range(num_folds):
    train_idx, test_idx = train_test_split(np.arange(N), test_size=0.1)
    train_idx, val_idx = train_test_split(train_idx, test_size=0.2)
    folds.append(Split(train=train_idx, valid=val_idx, test=test_idx))

In [5]:
df = ds.copy().loc[ds["ID"].isin(folds[0].train)]
df.ID  = LabelEncoder().fit_transform(df.ID)
df = df.sort_values(["Time", "ID"]).set_index("ID")

,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
ID,,,,,,,,,,,
6,0.0,0.0,0.0,0.0,-0.15843,0.0,False,False,False,True,False
7,0.0,-0.271953,0.0,0.0,0.0,0.0,True,False,False,False,False
22,0.0,0.0,0.0,0.0,-0.397128,0.0,False,False,False,True,False
30,0.0,0.0,0.0,-0.173762,0.0,0.0,False,False,True,False,False
41,0.0,0.0,0.0,-0.173762,0.0,-1.107072,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
775,200.0,0.0,0.0,0.0,-1.590619,0.0,False,False,False,True,False
777,200.0,0.0,-0.12797,0.0,0.0,0.0,False,True,False,False,False
778,200.0,0.0,0.0,0.0,0.0,-1.263596,False,False,False,False,True
787,200.0,0.0,0.0,0.0,-1.542879,0.0,False,False,False,True,False
793,200.0,0.0,-0.12797,0.0,0.0,0.0,False,True,False,False,False

In [6]:
import gru_ode_bayes
from gru_ode_bayes.data_utils import ODE_Dataset

In [7]:
ode_ds = ODE_Dataset(panda_df = ds, idx=folds[0].train )
ode_ds.df = ode_ds.df.sort_values(["Time", "ID"])
ode_ds.df

,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
ID,,,,,,,,,,,
6,0.0,0.000000,0.00000,0.000000,-0.158430,0.000000,0.0,0.0,0.0,1.0,0.0
7,0.0,-0.271953,0.00000,0.000000,0.000000,0.000000,1.0,0.0,0.0,0.0,0.0
22,0.0,0.000000,0.00000,0.000000,-0.397128,0.000000,0.0,0.0,0.0,1.0,0.0
30,0.0,0.000000,0.00000,-0.173762,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0
41,0.0,0.000000,0.00000,-0.173762,0.000000,-1.107072,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
775,200.0,0.000000,0.00000,0.000000,-1.590619,0.000000,0.0,0.0,0.0,1.0,0.0
777,200.0,0.000000,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0
778,200.0,0.000000,0.00000,0.000000,0.000000,-1.263596,0.0,0.0,0.0,0.0,1.0
787,200.0,0.000000,0.00000,0.000000,-1.542879,0.000000,0.0,0.0,0.0,1.0,0.0
793,200.0,0.000000,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0

In [8]:
df.loc[df.index == 0]

,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
ID,,,,,,,,,,,
0,0.3,0.0,-0.12797,0.0,0.0,0.0,False,True,False,False,False
0,0.6,0.0,-0.12797,0.0,0.0,0.0,False,True,False,False,False
0,0.7,0.0,0.0,0.0,0.0,0.614699,False,False,False,False,True
0,1.5,0.0,0.0,0.0,0.0,0.823399,False,False,False,False,True
0,1.9,0.0,0.0,0.0,0.318966,0.0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
0,198.899994,0.0,0.0,0.0,-0.970004,0.0,False,False,False,True,False
0,199.300003,0.0,0.0,0.0,-0.20617,0.0,False,False,False,True,False
0,199.5,0.0,0.0,-0.173762,0.0,0.0,False,False,True,False,False
0,199.699997,0.0,0.0,0.0,0.0,-0.533148,False,False,False,False,True
0,199.899994,0.0,0.0,0.0,0.0,-0.794022,False,False,False,False,True

In [9]:
ode_ds[0]["path"]

,Time,Value_0,Value_1,Value_2,Value_3,Value_4,Mask_0,Mask_1,Mask_2,Mask_3,Mask_4
ID,,,,,,,,,,,
0,0.300000,0.0,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0
0,0.600000,0.0,-0.12797,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,0.0
0,0.700000,0.0,0.00000,0.000000,0.000000,0.614699,0.0,0.0,0.0,0.0,1.0
0,1.500000,0.0,0.00000,0.000000,0.000000,0.823399,0.0,0.0,0.0,0.0,1.0
0,1.900000,0.0,0.00000,0.000000,0.318966,0.000000,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
0,198.899994,0.0,0.00000,0.000000,-0.970004,0.000000,0.0,0.0,0.0,1.0,0.0
0,199.300003,0.0,0.00000,0.000000,-0.206170,0.000000,0.0,0.0,0.0,1.0,0.0
0,199.500000,0.0,0.00000,-0.173762,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0
0,199.699997,0.0,0.00000,0.000000,0.000000,-0.533148,0.0,0.0,0.0,0.0,1.0
0,199.899994,0.0,0.00000,0.000000,0.000000,-0.794022,0.0,0.0,0.0,0.0,1.0