# Title

In [15]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [16]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, floatmode='fixed', suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7FC6EAE5EF20

In [17]:
from tsdm.datasets import ETTh1

In [18]:
ds = ETTh1.dataset

                       HUFL   HULL   MUFL   MULL   LUFL   LULL         OT
date
2016-07-01 00:00:00   5.827  2.009  1.599  0.462  4.203  1.340  30.531000
2016-07-01 01:00:00   5.693  2.076  1.492  0.426  4.142  1.371  27.787001
2016-07-01 02:00:00   5.157  1.741  1.279  0.355  3.777  1.218  27.787001
2016-07-01 03:00:00   5.090  1.942  1.279  0.391  3.807  1.279  25.044001
2016-07-01 04:00:00   5.358  1.942  1.492  0.462  3.868  1.279  21.948000
...                     ...    ...    ...    ...    ...    ...        ...
2018-06-26 15:00:00  -1.674  3.550 -5.615  2.132  3.472  1.523  10.904000
2018-06-26 16:00:00  -5.492  4.287 -9.132  2.274  3.533  1.675  11.044000
2018-06-26 17:00:00   2.813  3.818 -0.817  2.097  3.716  1.523  10.271000
2018-06-26 18:00:00   9.243  3.818  5.472  2.097  3.655  1.432   9.778000
2018-06-26 19:00:00  10.114  3.550  6.183  1.564  3.716  1.462   9.567000

[17420 rows x 7 columns]

In [19]:
import torch

In [20]:
torch.randn(3,4,5,6,7)[..., 3].shape

torch.Size([3, 4, 5, 6])

In [21]:
encs = {
    ('HUFL', 'HULL'): "A",
    ('MUFL', 'MULL'): "B",
    ('LUFL', 'LULL'): "C",
}

{('HUFL', 'HULL'): 'A', ('MUFL', 'MULL'): 'B', ('LUFL', 'LULL'): 'C'}

In [24]:
key = next(iter(encs))

('HUFL', 'HULL')

In [41]:
ds[*key]

SyntaxError: invalid syntax (545987766.py, line 1)

In [36]:
from pandas import DataFrame
DataFrame(columns=ds.columns)

Empty DataFrame
Columns: [HUFL, HULL, MUFL, MULL, LUFL, LULL, OT]
Index: []

In [49]:
(1,2, 3, 2).count(None)

0

In [130]:
from tsdm.tasks import KIWI_RUNS_TASK
task = KIWI_RUNS_TASK()

In [131]:
ts, md = task.splits((0, "train"))

In [132]:
ts["Temperature"].dtypes

Float32Dtype()

In [134]:
df = ts.reset_index(level=[0,1], drop=True)

,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2020-12-09 09:10:09,<NA>,<NA>,36.389999,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2020-12-09 09:10:19,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,7.27,<NA>,<NA>,<NA>
2020-12-09 09:10:24,<NA>,100.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2020-12-09 09:10:25,<NA>,<NA>,36.130001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2020-12-09 09:10:34,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,7.28,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-26 22:41:26,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0
2021-10-26 22:42:11,<NA>,<NA>,37.450001,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2021-10-26 22:42:20,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,79.459999,<NA>,<NA>,<NA>,7.320229,<NA>,<NA>,<NA>
2021-10-26 22:43:22,<NA>,<NA>,37.439999,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2021-10-26 22:43:31,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,78.860001,<NA>,<NA>,<NA>,7.336412,<NA>,<NA>,<NA>

In [140]:
task.preprocessor

ChainedEncoder[TensorEncoder(), DataFrameEncoder()]

In [142]:
task.preprocessor.fit(df)

In [145]:
enoded = task.preprocessor.encode(df)

(tensor([0.0000e+00, 1.0000e+01, 1.5000e+01,  ..., 2.7783e+07, 2.7783e+07,
         2.7783e+07], device='cuda:0'),
 tensor([[    nan,     nan, -1.7507,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan, -0.7491,     nan,  ...,     nan,     nan,     nan],
         ...,
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan],
         [    nan,     nan,  0.1846,  ...,     nan,     nan,     nan],
         [    nan,     nan,     nan,  ...,     nan,     nan,     nan]],
        device='cuda:0'))

In [144]:
task.preprocessor.decode(df)

AttributeError: 'str' object has no attribute 'cpu'

In [126]:
from pandas import NA, Index, DataFrame, Series



_colenc_spec = {
    "col": NA,
    "encoder": [1,2,3],
}

{'col': <NA>, 'encoder': [1, 2, 3]}

In [127]:
df = DataFrame(columns=["col", "encoder"], index=Index([], name="partition"))

Empty DataFrame
Columns: [col, encoder]
Index: []

In [129]:
df = df.append(Series(_colenc_spec, name="olga"))

            col    encoder
partition
olga       <NA>  [1, 2, 3]

In [110]:
Series(_colenc_spec)

parition            0
col              <NA>
encoder     [1, 2, 3]
dtype: object

In [97]:
df

Empty DataFrame
Columns: [col, encoder]
Index: []