In [1]:
import tsdm

In [2]:
x = tsdm.load_dataset('electricity')d
x

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,2.538071,22.048364,1.737619,150.406504,85.365854,303.571429,11.305822,282.828283,68.181818,72.043011,...,276.945039,28200.0,1616.033755,1363.636364,29.986962,5.851375,697.102722,176.961603,651.026393,7621.621622
2014-12-31 23:15:00,2.538071,21.337127,1.737619,166.666667,81.707317,324.404762,11.305822,252.525253,64.685315,72.043011,...,279.800143,28300.0,1569.620253,1340.909091,29.986962,9.947338,671.641791,168.614357,669.354839,6702.702703
2014-12-31 23:30:00,2.538071,20.625889,1.737619,162.601626,82.926829,318.452381,10.175240,242.424242,61.188811,74.193548,...,284.796574,27800.0,1556.962025,1318.181818,27.379400,9.362200,670.763828,153.589316,670.087977,6864.864865
2014-12-31 23:45:00,1.269036,21.337127,1.737619,166.666667,85.365854,285.714286,10.175240,225.589226,64.685315,72.043011,...,246.252677,28000.0,1443.037975,909.090909,26.075619,4.095963,664.618086,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,19.914651,1.737619,178.861789,84.146341,279.761905,10.175240,249.158249,62.937063,69.892473,...,188.436831,27800.0,1409.282700,954.545455,27.379400,4.095963,628.621598,131.886477,673.020528,7135.135135

In [3]:
tsdm.make_dense_triplets(x)

                    variable        value
time
2011-01-01 00:15:00   MT_001     0.000000
2011-01-01 00:15:00   MT_002     0.000000
2011-01-01 00:15:00   MT_003     0.000000
2011-01-01 00:15:00   MT_004     0.000000
2011-01-01 00:15:00   MT_005     0.000000
...                      ...          ...
2015-01-01 00:00:00   MT_366     4.095963
2015-01-01 00:00:00   MT_367   628.621598
2015-01-01 00:00:00   MT_368   131.886477
2015-01-01 00:00:00   MT_369   673.020528
2015-01-01 00:00:00   MT_370  7135.135135

[51894720 rows x 2 columns]

In [4]:
tsdm.make_sparse_triplets(x)

,value,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-01-01 00:00:00,4.095963,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2015-01-01 00:00:00,628.621598,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2015-01-01 00:00:00,131.886477,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
2015-01-01 00:00:00,673.020528,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2015-01-01 00:00:00,7135.135135,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [5]:
x, m, d = tsdm.make_masked_format(x)
display(x, m, d)

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:45:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 01:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,2.538071,22.048364,1.737619,150.406504,85.365854,303.571429,11.305822,282.828283,68.181818,72.043011,...,276.945039,28200.0,1616.033755,1363.636364,29.986962,5.851375,697.102722,176.961603,651.026393,7621.621622
2014-12-31 23:15:00,2.538071,21.337127,1.737619,166.666667,81.707317,324.404762,11.305822,252.525253,64.685315,72.043011,...,279.800143,28300.0,1569.620253,1340.909091,29.986962,9.947338,671.641791,168.614357,669.354839,6702.702703
2014-12-31 23:30:00,2.538071,20.625889,1.737619,162.601626,82.926829,318.452381,10.175240,242.424242,61.188811,74.193548,...,284.796574,27800.0,1556.962025,1318.181818,27.379400,9.362200,670.763828,153.589316,670.087977,6864.864865
2014-12-31 23:45:00,1.269036,21.337127,1.737619,166.666667,85.365854,285.714286,10.175240,225.589226,64.685315,72.043011,...,246.252677,28000.0,1443.037975,909.090909,26.075619,4.095963,664.618086,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,19.914651,1.737619,178.861789,84.146341,279.761905,10.175240,249.158249,62.937063,69.892473,...,188.436831,27800.0,1409.282700,954.545455,27.379400,4.095963,628.621598,131.886477,673.020528,7135.135135

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:30:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 01:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 01:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-31 23:15:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-31 23:30:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2014-12-31 23:45:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2015-01-01 00:00:00,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2011-01-01 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2011-01-01 00:45:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2011-01-01 01:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2011-01-01 01:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2014-12-31 23:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2014-12-31 23:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2014-12-31 23:45:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2015-01-01 00:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00