# tsdm.util.converters

In [1]:
%load_ext autoreload
%autoreload 2
import pandas

pandas.options.display.max_rows = 5

In [2]:
from tsdm.util.converters import make_dense_triplets, make_masked_format, make_sparse_triplets, triplet2dense, time2float, time2int,

In [3]:
from tsdm.datasets import Electricity

Electricity.dataset

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:45:00,1.269036,21.337127,1.737619,166.666667,85.365854,285.714286,10.17524,225.589226,64.685315,72.043011,...,246.252677,28000.0,1443.037975,909.090909,26.075619,4.095963,664.618086,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,19.914651,1.737619,178.861789,84.146341,279.761905,10.17524,249.158249,62.937063,69.892473,...,188.436831,27800.0,1409.282700,954.545455,27.379400,4.095963,628.621598,131.886477,673.020528,7135.135135

## make_dense_triplets

In [4]:
make_dense_triplets(Electricity.dataset)

                    variable        value
time
2011-01-01 00:15:00   MT_001     0.000000
2011-01-01 00:15:00   MT_002     0.000000
...                      ...          ...
2015-01-01 00:00:00   MT_369   673.020528
2015-01-01 00:00:00   MT_370  7135.135135

[51894720 rows x 2 columns]

## make_sparse_triplets

In [5]:
make_sparse_triplets(Electricity.dataset)

,value,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2011-01-01 00:15:00,0.000000,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015-01-01 00:00:00,673.020528,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2015-01-01 00:00:00,7135.135135,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## make_masked_format

In [8]:
x, mask, delta = make_masked_format(Electricity.dataset)
display(x, mask, delta)

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2011-01-01 00:30:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:45:00,1.269036,21.337127,1.737619,166.666667,85.365854,285.714286,10.17524,225.589226,64.685315,72.043011,...,246.252677,28000.0,1443.037975,909.090909,26.075619,4.095963,664.618086,146.911519,646.627566,6540.540541
2015-01-01 00:00:00,2.538071,19.914651,1.737619,178.861789,84.146341,279.761905,10.17524,249.158249,62.937063,69.892473,...,188.436831,27800.0,1409.282700,954.545455,27.379400,4.095963,628.621598,131.886477,673.020528,7135.135135

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2011-01-01 00:30:00,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:45:00,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2015-01-01 00:00:00,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

client,MT_001,MT_002,MT_003,MT_004,MT_005,MT_006,MT_007,MT_008,MT_009,MT_010,...,MT_361,MT_362,MT_363,MT_364,MT_365,MT_366,MT_367,MT_368,MT_369,MT_370
time,,,,,,,,,,,,,,,,,,,,,
2011-01-01 00:15:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,...,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2011-01-01 00:30:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2014-12-31 23:45:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00
2015-01-01 00:00:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,...,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00,0 days 00:15:00

## time2float

In [9]:
time2float(Electricity.dataset.index)

Float64Index([     0.0,      1.0,      2.0,      3.0,      4.0,      5.0,
                   6.0,      7.0,      8.0,      9.0,
              ...
              140246.0, 140247.0, 140248.0, 140249.0, 140250.0, 140251.0,
              140252.0, 140253.0, 140254.0, 140255.0],
             dtype='float64', name='time', length=140256)

## time2int

In [11]:
time2int(Electricity.dataset.index)

Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                 8,      9,
            ...
            140246, 140247, 140248, 140249, 140250, 140251, 140252, 140253,
            140254, 140255],
           dtype='int64', name='time', length=140256)

## triplet2dense

In [12]:
triplet2dense(Electricity.dataset)

NotImplementedError: