# Small Example what a Task Object can do

In [1]:
# some setup code
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging

logging.basicConfig(level=logging.INFO)

In [2]:
from tsdm.tasks import KIWI_RUNS_TASK

INFO:numexpr.utils:Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
INFO:tsdm.config._config:Available Models: {'BRITS', 'TFT', 'NCDE', 'TPA', 'GRU-ODE-Bayes', 'ODE-RNN', 'mTAN', 'N-BEATS', 'Informer', 'M-RNN', 'Latent-ODE', 'SET-TS', 'NODE', 'IP-Net'}
INFO:tsdm.config._config:Available Datasets: {'Air Quality', 'USHCN', 'Traffic', 'M3', 'Physionet 2012', 'Human Activity', 'Physionet 2019', 'tourism2', 'UWAVE', 'Electricity', 'tourism1', 'Air Quality Multi-Site', 'MuJoCo', 'Household Consumption', 'Character Trajectories', 'M4', 'M5'}
INFO:tsdm.config._config:Initializing folder structure
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/datasets
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/models
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/logs
INFO:tsdm.config._config:creating folder /home/rscholz/.tsdm/rawdata
INFO:tsdm.config._config:Created folder structure in /home/rscholz/.tsdm

In [3]:
task = KIWI_RUNS_TASK()

INFO:tsdm.datasets.base._base:KIWI_RUNS: START cleaning dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS/units already exists, skipping.
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE cleaning dataset
INFO:tsdm.datasets.base._base:KIWI_RUNS: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/timeseries: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/metadata: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: START loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS/units: DONE loading dataset!
INFO:tsdm.datasets.base._base:KIWI_RUNS: DONE loading dataset!

KIWI_RUNS_TASK(dataset=KIWI_RUNS, test_metric=WRMSE)

### Attributes and Methods

## Note: The .dataset attribute contains the **original** dataset without any task-specific modifications.

In [5]:
task.dataset

KIWI_RUNS['timeseries', 'metadata', 'units']

Whereas the **`.timeseries`** **`.metadata`** and **`.unit`** attributes contain the task-specific preprocessed versions of these datasets

In [6]:
assert 355 in task.dataset.timeseries.index
assert 355 not in task.index
task.timeseries

variable                                  Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09       0.0            0.0
                     2020-12-09 09:10:19       0.0            0.0
                     2020-12-09 09:10:24       0.0          100.0
                     2020-12-09 09:10:25       0.0          100.0
                     2020-12-09 09:10:34       0.0          100.0
...                                            ...            ...
510    16871         2021-10-26 22:41:26       5.0            0.0
                     2021-10-26 22:42:11       5.0            0.0
                     2021-10-26 22:42:20       5.0            0.0
                     2021-10-26 22:43:22       5.0            0.0
                     2021-10-26 22:43:31       5.0            0.0

variable                                  Temperature  Acetate  Base  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09    36.389999     <NA>  <NA>
                     2020-12-09 09:10:19         <NA>     <NA>  <NA>
                     2020-12-09 09:10:24         <NA>     <NA>  <NA>
                     2020-12-09 09:10:25    36.130001     <NA>  <NA>
                     2020-12-09 09:10:34         <NA>     <NA>  <NA>
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26         <NA>     <NA>  <NA>
                     2021-10-26 22:42:11    37.450001     <NA>  <NA>
                     2021-10-26 22:42:20         <NA>     <NA>  <NA>
                     2021-10-26 22:43:22    37.439999     <NA>  <NA>
                     2021-10-26 22:43:31         <NA>     <NA>  <NA>

variable                                  Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                            0.0
                     2020-12-09 09:10:19                            0.0
                     2020-12-09 09:10:24                            0.0
                     2020-12-09 09:10:25                            0.0
                     2020-12-09 09:10:34                            0.0
...                                                                 ...
510    16871         2021-10-26 22:41:26                         1061.0
                     2021-10-26 22:42:11                         1061.0
                     2021-10-26 22:42:20                         1061.0
                     2021-10-26 22:43:22                         1061.0
                     2021-10-26 22:43:31                         1061.0

variable                                  Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                           0.0
                     2020-12-09 09:10:19                           0.0
                     2020-12-09 09:10:24                           0.0
                     2020-12-09 09:10:25                           0.0
                     2020-12-09 09:10:34                           0.0
...                                                                ...
510    16871         2021-10-26 22:41:26                   3787.307373
                     2021-10-26 22:42:11                   3787.307373
                     2021-10-26 22:42:20                   3787.307373
                     2021-10-26 22:43:22                   3787.307373
                     2021-10-26 22:43:31                   3787.307373

variable                                        DOT  Glucose  OD600  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09       <NA>     <NA>   <NA>
                     2020-12-09 09:10:19        0.0     <NA>   <NA>
                     2020-12-09 09:10:24       <NA>     <NA>   <NA>
                     2020-12-09 09:10:25       <NA>     <NA>   <NA>
                     2020-12-09 09:10:34        0.0     <NA>   <NA>
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26       <NA>     <NA>   <NA>
                     2021-10-26 22:42:11       <NA>     <NA>   <NA>
                     2021-10-26 22:42:20  79.459999     <NA>   <NA>
                     2021-10-26 22:43:22       <NA>     <NA>   <NA>
                     2021-10-26 22:43:31  78.860001     <NA>   <NA>

variable                                  Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09           0.0      <NA>      <NA>
                     2020-12-09 09:10:19           0.0      7.27      <NA>
                     2020-12-09 09:10:24           0.0      <NA>      <NA>
                     2020-12-09 09:10:25           0.0      <NA>      <NA>
                     2020-12-09 09:10:34           0.0      7.28      <NA>
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26        5500.0      <NA>      <NA>
                     2021-10-26 22:42:11        5500.0      <NA>      <NA>
                     2021-10-26 22:42:20        5500.0  7.320229      <NA>
                     2021-10-26 22:43:22        5500.0      <NA>      <NA>
                     2021-10-26 22:43:31        5500.0  7.336412      <NA>

variable                                  InducerConcentration      Volume
run_id experiment_id measurement_time
439    15325         2020-12-09 09:10:09                   0.0        <NA>
                     2020-12-09 09:10:19                   0.0        <NA>
                     2020-12-09 09:10:24                   0.0        <NA>
                     2020-12-09 09:10:25                   0.0        <NA>
                     2020-12-09 09:10:34                   0.0        <NA>
...                                                        ...         ...
510    16871         2021-10-26 22:41:26                   0.0 -312.692749
                     2021-10-26 22:42:11                   0.0        <NA>
                     2021-10-26 22:42:20                   0.0        <NA>
                     2021-10-26 22:43:22                   0.0        <NA>
                     2021-10-26 22:43:31                   0.0        <NA>

[324957 rows x 15 columns]

The attributes `.split`, `.split_idx` contain information about the splits

In [7]:
task.split_idx

split                     0      1      2      3      4
run_id experiment_id
439    15325          train  train  train  train  train
       15326          train  train  train  train  train
       15327          train   test  train  train  train
       15328          train  train   test   test  train
       15329          train  train  train  train  train
...                     ...    ...    ...    ...    ...
510    16867          train  train   test  train  train
       16868          train   test  train  train   test
       16869          train  train  train  train  train
       16870          train   test  train  train   test
       16871          train  train   test  train   test

[216 rows x 5 columns]

### `.batchloaders` and `.datalaoders` are lazily loaded dictionaries

In [8]:
task.dataloaders

LazyDict(
  (0, 'train'): <LazyFunction: get_dataloader>
  (0, 'test') : <LazyFunction: get_dataloader>
  (1, 'train'): <LazyFunction: get_dataloader>
  (1, 'test') : <LazyFunction: get_dataloader>
  (2, 'train'): <LazyFunction: get_dataloader>
  (2, 'test') : <LazyFunction: get_dataloader>
  (3, 'train'): <LazyFunction: get_dataloader>
  (3, 'test') : <LazyFunction: get_dataloader>
  (4, 'train'): <LazyFunction: get_dataloader>
  (4, 'test') : <LazyFunction: get_dataloader>
)

In [9]:
dataloader = task.dataloaders[(2, "test")]

In [10]:
task.dataloaders

LazyDict(
  (0, 'train'): <LazyFunction: get_dataloader>
  (0, 'test') : <LazyFunction: get_dataloader>
  (1, 'train'): <LazyFunction: get_dataloader>
  (1, 'test') : <LazyFunction: get_dataloader>
  (2, 'train'): <LazyFunction: get_dataloader>
  (2, 'test') : <torch.utils.data.dataloader.DataLoader object at 0x7f5b3e1af1f0>
  (3, 'train'): <LazyFunction: get_dataloader>
  (3, 'test') : <LazyFunction: get_dataloader>
  (4, 'train'): <LazyFunction: get_dataloader>
  (4, 'test') : <LazyFunction: get_dataloader>
)

### Each dataloader has a **`.preprocessor`** attribute which is a copy of the task-specific preprocessor fitted on the training data corresponding on the selected split

In [11]:
dataloader.preprocessor

ChainedEncoder[TensorEncoder(), DataFrameEncoder(                                                                 col  \
section partition
index   0                                                       <NA>
columns 0          [Flow_Air, StirringSpeed, Temperature, Acetate...

                                                encoder
section partition
index   0               (MinMaxScaler, DateTimeEncoder)
columns 0          (Standardizer([-1]), FloatEncoder())
)]

In [12]:
batch = next(iter(dataloader))
T, X = batch
T.shape, X.shape

(torch.Size([128, 120]), torch.Size([128, 120, 15]))

#### The preprocessor can be used to recover the original unencoded data. This does not work in batch-mode at the moment!

In [13]:
t, x = T[0], X[0]
t, x

(tensor([0.4105, 0.4105, 0.4105, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106,
         0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4106, 0.4107, 0.4107, 0.4107,
         0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107,
         0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107,
         0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107, 0.4107,
         0.4107, 0.4107, 0.4107], device='cuda:0'),
 tensor([[-2.9278,  2.2687,     nan,  ...,     nan, -0.4377,     nan],
         [-0.3877,  2.2687,     nan,  ...,     nan, -0.4377,     nan],
         [-0.3877,  2.2687,     nan,  ...,     nan, -0.4377,     nan],
         ...,
         [-0.3877, -0.4862,     nan,  ...,     nan, -0.4377,     nan],
         [-0.3877, -0.4862,     nan,  ...,     nan, -0.4377,     nan],
         [-0.3877, -0.4862,  0.5127,  ...,     nan, -0.4377,     nan]],
        device='cuda:0'))

In [14]:
dataloader.preprocessor.decode((t, x))

s

,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2021-04-20 09:27:55,0.0,2600.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2021-04-20 09:28:07,5.0,2600.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2021-04-20 09:35:14,5.0,2600.0,<NA>,<NA>,<NA>,0.0,6.18335,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2021-04-20 09:39:27,5.0,2600.0,<NA>,<NA>,<NA>,0.0,6.18335,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2021-04-20 09:40:02,5.0,2400.000244,<NA>,<NA>,<NA>,0.0,6.18335,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-04-20 10:40:31,5.0,0.0,<NA>,<NA>,<NA>,0.0,6.18335,100.0,<NA>,<NA>,0.0,6.98,<NA>,0.0,<NA>
2021-04-20 10:41:31,5.0,0.0,37.59,<NA>,<NA>,0.0,6.18335,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2021-04-20 10:41:41,5.0,0.0,<NA>,<NA>,<NA>,0.0,6.18335,99.779999,<NA>,<NA>,0.0,6.97,<NA>,0.0,<NA>
2021-04-20 10:42:52,5.0,0.0,<NA>,<NA>,<NA>,0.0,6.18335,99.629997,<NA>,<NA>,0.0,6.95,<NA>,0.0,<NA>
2021-04-20 10:43:53,5.0,0.0,37.599998,<NA>,<NA>,0.0,6.18335,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>

TODO: include the hierarchical indices