# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging
logging.basicConfig(level=logging.INFO)

In [5]:
from itertools import product
from time import perf_counter

import gc
import numpy as np
import torch
import pandas as pd
from pandas import DataFrame, MultiIndex, Series
from tqdm.auto import tqdm

np.set_printoptions(precision=4, floatmode="fixed", suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7F4D67D7EF20

In [3]:
reductions = []
for a,b in product("ijkl", "ijkl"):
    if a==b: continue
    reduction = f"{a}{b},ijkl->" + "ijkl".replace(a, "").replace(b, "")
    reductions.append(reduction)

framework = ["numpy", "torch"]
dtypes = ["int32", "int64", "float32", "float64"]
sizes = [64, 128, 256]

TORCH_DTYPES = {"int32": torch.int32, "int64": torch.int64, "float32": torch.float32, "float64": torch.float64}

devices = [torch.device("cpu"), torch.device("cuda")]
columns = Series(reductions, name="reduction")
index = MultiIndex.from_product(
    [sizes, dtypes, framework], names=["size", "dtype", "framework"]
)
results = DataFrame(index=index, columns=columns, dtype=float)

reduction               ij,ijkl->kl  ik,ijkl->jl  il,ijkl->jk  ji,ijkl->kl  \
size dtype   framework
64   int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
128  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
256  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN

reduction               jk,ijkl->il  jl,ijkl->ik  ki,ijkl->jl  kj,ijkl->il  \
size dtype   framework
64   int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
128  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
256  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN

reduction               kl,ijkl->ij  li,ijkl->jk  lj,ijkl->ik  lk,ijkl->ij
size dtype   framework
64   int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
128  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
256  int32   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     int64   numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float32 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN
     float64 numpy              NaN          NaN          NaN          NaN
             torch              NaN          NaN          NaN          NaN

In [ ]:
# torch_results
for size in tqdm(sizes):
    _mat1 = torch.randn((size, size, size, size), device="cpu")
    _mat2 = torch.randn((size, size), device="cpu")

    for dtype in tqdm(dtypes, leave=False):
        mat1 = _mat1.to(dtype=TORCH_DTYPES[dtype])
        mat2 = _mat2.to(dtype=TORCH_DTYPES[dtype])

        for reduction in tqdm(reductions, leave=False):
            gc.disable()
            start = perf_counter()
            torch.einsum(reduction, mat2, mat1)
            stop = perf_counter()
            gc.enable()
            results.loc[(size, dtype, "torch"), reduction] = stop - start

In [ ]:
# numpy results
for size in tqdm(sizes):
    _mat1 = np.random.normal(size=(size, size, size, size))
    _mat2 = np.random.normal(size=(size, size))

    for dtype in tqdm(dtypes, leave=False):
        mat1 = _mat1.astype(dtype)
        mat2 = _mat2.astype(dtype)

        for reduction in tqdm(reductions, leave=False):
            gc.disable()
            start = perf_counter()
            np.einsum(reduction, mat2, mat1, optimize=False)
            stop = perf_counter()
            gc.enable()
            results.loc[(size, dtype, "numpy"), reduction] = stop - start

In [ ]:
results.round(3).sort_values(["size", "dtype", "framework"])

In [72]:
results = pd.read_csv("einsum_slow.csv")
results = results.set_index(["size", "dtype", "lib"])
results.columns = results.columns.rename("reduction")
results = results.transpose()
results = results.sort_values(by=[(256, "float64", "numpy"),(256, "float32", "numpy")])

size            64                            128                        \
dtype       float32        float64        float32        float64
lib           numpy  torch   numpy  torch   numpy  torch   numpy  torch
reduction
ji,ijkl->kl   0.003  0.003   0.006  0.005   0.046  0.041   0.093  0.083
jk,ijkl->il   0.004  0.012   0.006  0.023   0.051  0.181   0.094  0.329
ij,ijkl->kl   0.003  0.003   0.006  0.006   0.047  0.042   0.093  0.084
il,ijkl->jk   0.004  0.014   0.007  0.024   0.052  0.244   0.103  0.567
kl,ijkl->ij   0.004  0.003   0.007  0.005   0.056  0.043   0.113  0.084
jl,ijkl->ik   0.004  0.013   0.007  0.024   0.058  0.232   0.109  0.546
kj,ijkl->il   0.010  0.012   0.010  0.023   0.155  0.174   0.159  0.338
ik,ijkl->jl   0.010  0.013   0.010  0.024   0.154  0.175   0.160  0.329
ki,ijkl->jl   0.010  0.012   0.010  0.023   0.154  0.173   0.160  0.328
lk,ijkl->ij   0.009  0.003   0.011  0.006   0.277  0.041   0.295  0.082
li,ijkl->jk   0.009  0.013   0.011  0.023   0.294  0.189   0.311  0.606
lj,ijkl->ik   0.010  0.013   0.012  0.024   0.298  0.209   0.319  0.571

size            256
dtype       float32        float64
lib           numpy  torch   numpy   torch
reduction
ji,ijkl->kl   0.749  0.838   1.505   1.311
jk,ijkl->il   0.771  2.603   1.506   5.120
ij,ijkl->kl   0.747  0.818   1.514   1.291
il,ijkl->jk   0.844  9.077   1.774  11.226
kl,ijkl->ij   0.915  0.763   1.808   1.295
jl,ijkl->ik   0.909  9.226   1.818  11.279
kj,ijkl->il   2.329  2.610   2.454   5.132
ik,ijkl->jl   2.330  2.752   2.458   5.177
ki,ijkl->jl   2.330  2.676   2.467   5.145
lk,ijkl->ij   4.384  0.736   7.909   1.309
li,ijkl->jk   4.670  9.068   8.684  11.258
lj,ijkl->ik   4.701  9.305   8.720  11.407

In [73]:
results.loc["min"] = results.min()
results.loc["max"] = results.max()
results.loc["ratio"] = results.loc["max"]/results.loc["min"]

In [74]:
results

size              64                                 128                     \
dtype         float32           float64          float32            float64
lib             numpy     torch   numpy  torch     numpy    torch     numpy
reduction
ji,ijkl->kl  0.003000  0.003000   0.006  0.005  0.046000  0.04100  0.093000
jk,ijkl->il  0.004000  0.012000   0.006  0.023  0.051000  0.18100  0.094000
ij,ijkl->kl  0.003000  0.003000   0.006  0.006  0.047000  0.04200  0.093000
il,ijkl->jk  0.004000  0.014000   0.007  0.024  0.052000  0.24400  0.103000
kl,ijkl->ij  0.004000  0.003000   0.007  0.005  0.056000  0.04300  0.113000
jl,ijkl->ik  0.004000  0.013000   0.007  0.024  0.058000  0.23200  0.109000
kj,ijkl->il  0.010000  0.012000   0.010  0.023  0.155000  0.17400  0.159000
ik,ijkl->jl  0.010000  0.013000   0.010  0.024  0.154000  0.17500  0.160000
ki,ijkl->jl  0.010000  0.012000   0.010  0.023  0.154000  0.17300  0.160000
lk,ijkl->ij  0.009000  0.003000   0.011  0.006  0.277000  0.04100  0.295000
li,ijkl->jk  0.009000  0.013000   0.011  0.023  0.294000  0.18900  0.311000
lj,ijkl->ik  0.010000  0.013000   0.012  0.024  0.298000  0.20900  0.319000
min          0.003000  0.003000   0.006  0.005  0.046000  0.04100  0.093000
max          0.010000  0.014000   0.012  0.024  0.298000  0.24400  0.319000
ratio        3.333333  4.666667   2.000  4.800  6.478261  5.95122  3.430108

size                        256
dtype                   float32             float64
lib             torch     numpy      torch    numpy      torch
reduction
ji,ijkl->kl  0.083000  0.749000   0.838000  1.50500   1.311000
jk,ijkl->il  0.329000  0.771000   2.603000  1.50600   5.120000
ij,ijkl->kl  0.084000  0.747000   0.818000  1.51400   1.291000
il,ijkl->jk  0.567000  0.844000   9.077000  1.77400  11.226000
kl,ijkl->ij  0.084000  0.915000   0.763000  1.80800   1.295000
jl,ijkl->ik  0.546000  0.909000   9.226000  1.81800  11.279000
kj,ijkl->il  0.338000  2.329000   2.610000  2.45400   5.132000
ik,ijkl->jl  0.329000  2.330000   2.752000  2.45800   5.177000
ki,ijkl->jl  0.328000  2.330000   2.676000  2.46700   5.145000
lk,ijkl->ij  0.082000  4.384000   0.736000  7.90900   1.309000
li,ijkl->jk  0.606000  4.670000   9.068000  8.68400  11.258000
lj,ijkl->ik  0.571000  4.701000   9.305000  8.72000  11.407000
min          0.082000  0.747000   0.736000  1.50500   1.291000
max          0.606000  4.701000   9.305000  8.72000  11.407000
ratio        7.390244  6.293173  12.642663  5.79402   8.835786

In [76]:
results.loc[...,  (slice(None), slice(None), "numpy")].round(2)

size            64              128             256
dtype       float32 float64 float32 float64 float32 float64
lib           numpy   numpy   numpy   numpy   numpy   numpy
reduction
ji,ijkl->kl    0.00    0.01    0.05    0.09    0.75    1.50
jk,ijkl->il    0.00    0.01    0.05    0.09    0.77    1.51
ij,ijkl->kl    0.00    0.01    0.05    0.09    0.75    1.51
il,ijkl->jk    0.00    0.01    0.05    0.10    0.84    1.77
kl,ijkl->ij    0.00    0.01    0.06    0.11    0.92    1.81
jl,ijkl->ik    0.00    0.01    0.06    0.11    0.91    1.82
kj,ijkl->il    0.01    0.01    0.16    0.16    2.33    2.45
ik,ijkl->jl    0.01    0.01    0.15    0.16    2.33    2.46
ki,ijkl->jl    0.01    0.01    0.15    0.16    2.33    2.47
lk,ijkl->ij    0.01    0.01    0.28    0.30    4.38    7.91
li,ijkl->jk    0.01    0.01    0.29    0.31    4.67    8.68
lj,ijkl->ik    0.01    0.01    0.30    0.32    4.70    8.72
min            0.00    0.01    0.05    0.09    0.75    1.50
max            0.01    0.01    0.30    0.32    4.70    8.72
ratio          3.33    2.00    6.48    3.43    6.29    5.79

In [71]:
results.loc[...,  (slice(None), slice(None), "numpy")].round(2)

size            64              128             256
dtype       float32 float64 float32 float64 float32 float64
lib           numpy   numpy   numpy   numpy   numpy   numpy
reduction
ij,ijkl->kl    0.00    0.01    0.05    0.09    0.75    1.51
kl,ijkl->ij    0.00    0.01    0.06    0.11    0.92    1.81
lk,ijkl->ij    0.01    0.01    0.28    0.30    4.38    7.91
ji,ijkl->kl    0.00    0.01    0.05    0.09    0.75    1.50
jk,ijkl->il    0.00    0.01    0.05    0.09    0.77    1.51
kj,ijkl->il    0.01    0.01    0.16    0.16    2.33    2.45
ki,ijkl->jl    0.01    0.01    0.15    0.16    2.33    2.47
ik,ijkl->jl    0.01    0.01    0.15    0.16    2.33    2.46
il,ijkl->jk    0.00    0.01    0.05    0.10    0.84    1.77
li,ijkl->jk    0.01    0.01    0.29    0.31    4.67    8.68
jl,ijkl->ik    0.00    0.01    0.06    0.11    0.91    1.82
lj,ijkl->ik    0.01    0.01    0.30    0.32    4.70    8.72
min            0.00    0.01    0.05    0.09    0.75    1.50
max            0.01    0.01    0.30    0.32    4.70    8.72
ratio          3.33    2.00    6.48    3.43    6.29    5.79