# Title

In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

import logging

logging.basicConfig(level=logging.INFO)

In [29]:
import os
from itertools import product
from time import perf_counter

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import gc

import jax
import mxnet as mx
import numpy as np
import pandas as pd
import tensorflow as tf
import torch
import opt_einsum
from opt_einsum import contract
from pandas import DataFrame, MultiIndex, Series
from tqdm.auto import tqdm

jax.config.update("jax_platform_name", "cpu")
# jax.config.update("jax_enable_x64", True)
np.set_printoptions(precision=4, floatmode="fixed", suppress=True)
rng = np.random.default_rng()

Generator(PCG64) at 0x7FE7282924A0

In [3]:
reductions = []
for a, b in product("ijkl", "ijkl"):
    if a == b:
        continue
    reduction = f"{a}{b},ijkl->" + "ijkl".replace(a, "").replace(b, "")
    reductions.append(reduction)

libs = ["contrat", "numpy", "torch", "jax", "tf", "mx"]
dtypes = ["float32"]
sizes = [64, 128, 256]

TORCH_DTYPES = {
    "int32": torch.int32,
    "int64": torch.int64,
    "float32": torch.float32,
    "float64": torch.float64,
}

devices = [torch.device("cpu"), torch.device("cuda")]
index = Series(reductions, name="reduction")
columns = MultiIndex.from_product([sizes, dtypes, libs], names=["size", "dtype", "lib"])
results = DataFrame(index=index, columns=columns, dtype=float)

size            64                128               256
dtype       float32           float32           float32
lib           numpy torch jax   numpy torch jax   numpy torch jax
reduction
ij,ijkl->kl     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
ik,ijkl->jl     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
il,ijkl->jk     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
ji,ijkl->kl     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
jk,ijkl->il     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
jl,ijkl->ik     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
ki,ijkl->jl     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
kj,ijkl->il     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
kl,ijkl->ij     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
li,ijkl->jk     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
lj,ijkl->ik     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN
lk,ijkl->ij     NaN   NaN NaN     NaN   NaN NaN     NaN   NaN NaN

In [4]:
# jax results
for size in tqdm(sizes):
    _mat1 = np.random.normal(size=(size, size, size, size))
    _mat2 = np.random.normal(size=(size, size))

    for dtype in tqdm(dtypes, leave=False):
        mat1 = jax.numpy.array(_mat1, dtype=dtype)
        mat2 = jax.numpy.array(_mat2, dtype=dtype)

        for reduction in tqdm(reductions, leave=False):
            gc.disable()
            start = perf_counter()
            jax.numpy.einsum(reduction, mat2, mat1)
            stop = perf_counter()
            gc.enable()
            results.loc[reduction, (size, dtype, "jax")] = stop - start

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

INFO:absl:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
INFO:absl:Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

In [5]:
# torch_results
for size in tqdm(sizes):
    _mat1 = torch.randn((size, size, size, size), device="cpu")
    _mat2 = torch.randn((size, size), device="cpu")

    for dtype in tqdm(dtypes, leave=False):
        mat1 = _mat1.to(dtype=TORCH_DTYPES[dtype])
        mat2 = _mat2.to(dtype=TORCH_DTYPES[dtype])

        for reduction in tqdm(reductions, leave=False):
            gc.disable()
            start = perf_counter()
            torch.einsum(reduction, mat2, mat1)
            stop = perf_counter()
            gc.enable()
            results.loc[reduction, (size, dtype, "torch")] = stop - start

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

In [6]:
# numpy results
for size in tqdm(sizes):
    _mat1 = np.random.normal(size=(size, size, size, size))
    _mat2 = np.random.normal(size=(size, size))

    for dtype in tqdm(dtypes, leave=False):
        mat1 = _mat1.astype(dtype)
        mat2 = _mat2.astype(dtype)

        for reduction in tqdm(reductions, leave=False):
            gc.disable()
            start = perf_counter()
            np.einsum(reduction, mat2, mat1, optimize=False)
            stop = perf_counter()
            gc.enable()
            results.loc[reduction, (size, dtype, "numpy")] = stop - start

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/12 [00:00<?, ?it/s]

In [ ]:
# tensorflow results

In [17]:
results = results.round(3).sort_values(by=[(256, "float32", "jax")])
results.to_csv("einsum_slow_jax.csv")

In [18]:
results.round(2).sort_values(by=[(256, "float32", "jax")])

size            64                  128                 256
dtype       float32             float32             float32
lib           numpy torch   jax   numpy torch   jax   numpy  torch    jax
reduction
ij,ijkl->kl    0.00  0.01  0.02    0.05  0.05  0.06    0.75   0.76   0.70
ji,ijkl->kl    0.00  0.00  0.02    0.05  0.05  0.06    0.75   0.76   0.70
jk,ijkl->il    0.00  0.01  0.03    0.05  0.20  0.26    0.77   2.75   2.78
kj,ijkl->il    0.01  0.01  0.04    0.16  0.20  0.22    2.33   2.80   2.87
ik,ijkl->jl    0.01  0.02  0.03    0.15  0.19  0.22    2.35   2.84   2.94
ki,ijkl->jl    0.01  0.01  0.04    0.15  0.20  0.22    2.34   2.78   3.07
li,ijkl->jk    0.01  0.01  0.04    0.29  0.23  0.26    4.61  10.14   9.66
il,ijkl->jk    0.00  0.02  0.04    0.06  0.22  0.28    0.82   9.98   9.86
lj,ijkl->ik    0.01  0.01  0.04    0.30  0.23  0.27    4.66   9.62  10.02
jl,ijkl->ik    0.00  0.02  0.04    0.06  0.22  0.25    0.90  10.07  10.08
lk,ijkl->ij    0.01  0.00  0.07    0.28  0.04  0.82    4.27   0.76  59.20
kl,ijkl->ij    0.00  0.00  0.06    0.06  0.05  0.83    0.90   0.76  62.52

In [30]:
import jaxlib

print(
    f"{np.__version__=}",
    f"{opt_einsum.__version__=}",
    f"{torch.__version__=}",
    f"{jax.__version__=}",
    f"{jaxlib.__version__=}",
    f"{tf.__version__=}",
    f"{mx.__version__=}",
    sep="\n",
)

np.__version__='1.21.5'
opt_einsum.__version__='v3.3.0'
torch.__version__='1.10.2'
jax.__version__='0.2.21'
jaxlib.__version__='0.1.76'
tf.__version__='2.8.0'
mx.__version__='2.0.0'

In [ ]:
results = pd.read_csv("einsum_slow.csv")
results = results.set_index(["size", "dtype", "lib"])
results.columns = results.columns.rename("reduction")
results = results.transpose()
results = results.sort_values(by=[(256, "float64", "numpy"), (256, "float32", "numpy")])

In [ ]:
results.loc["min"] = results.min()
results.loc["max"] = results.max()
results.loc["ratio"] = results.loc["max"] / results.loc["min"]

In [ ]:
results

In [ ]:
results.loc[..., (slice(None), slice(None), "numpy")].round(2)

In [ ]:
results.loc[..., (slice(None), slice(None), "numpy")].round(2)