In [7]:
encoder = ChainedEncoder(
    # 
    TensorEncoder(),
    # FrameSplitter(["value", "measurement_time", ["OD600", "Acetate"], ...]),
    FrameSplitter([...]),
    TripletEncoder(),
    FrameEncoder(
        Standardizer(),
        index_encoders=MinMaxScaler() @ TimeDeltaEncoder(unit="s"),
    ),
)

ChainedEncoder(
    TensorEncoder(),
    FrameSplitter(
        0: Ellipsis,
    ),
    TripletEncoder(),
    FrameEncoder(
        column_encoders: Standardizer(axis=None),
        index_encoders: ChainedEncoder(
            MinMaxScaler(axis=None),
            TimeDeltaEncoder(unit='s'),
        ),
    ),
)

In [8]:
data = ts.loc[439,15325]

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
0 days 00:00:11,0.0,0.0,36.389999,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
0 days 00:00:21,0.0,0.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.27,NaN,0.00,NaN
0 days 00:00:26,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
0 days 00:00:27,0.0,100.0,36.130001,NaN,NaN,0.0,0.000000,NaN,NaN,NaN,0.0,NaN,NaN,0.00,NaN
0 days 00:00:36,0.0,100.0,NaN,NaN,NaN,0.0,0.000000,0.000000,NaN,NaN,0.0,7.28,NaN,0.00,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0 days 14:21:42,10.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.720001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
0 days 14:21:44,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN
0 days 14:21:53,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,52.950001,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
0 days 14:22:04,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,53.240002,NaN,NaN,3600.0,6.44,NaN,0.05,NaN
0 days 14:22:07,0.0,0.0,NaN,NaN,NaN,2431.0,2188.030029,NaN,NaN,NaN,3600.0,NaN,NaN,0.05,NaN

In [9]:
encoder.fit(data)
encoded = encoder.encode(data)

/home/rscholz/Projects/KIWI/tsdm/tsdm/encoders/modular/_modular.py:726: RuntimeWarning: Mean of empty slice
  self.mean = np.nanmean(data, axis=axes)
/home/rscholz/miniconda3/envs/kiwi/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1670: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

(tensor([[ 0.0000, -2.5575,  1.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000, -0.7406,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 0.0000, -0.7179,  0.0000,  ...,  0.0000,  1.0000,  0.0000],
         ...,
         [ 1.0000, -0.1531,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 1.0000,  0.9843,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
         [ 1.0000,  1.3930,  0.0000,  ...,  0.0000,  1.0000,  0.0000]]),)

In [11]:
decoded = encoder.decode(encoded)

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
0 days 00:00:11,3.069337e-09,2.482298e-08,36.389999,NaN,NaN,-0.000008,0.000044,NaN,NaN,NaN,0.000036,NaN,NaN,3.630255e-10,NaN
0 days 00:00:21,3.069337e-09,2.482298e-08,NaN,NaN,NaN,-0.000008,0.000044,-0.000002,NaN,NaN,0.000036,7.27,NaN,3.630255e-10,NaN
0 days 00:00:26,3.069337e-09,1.000000e+02,NaN,NaN,NaN,-0.000008,0.000044,NaN,NaN,NaN,0.000036,NaN,NaN,3.630255e-10,NaN
0 days 00:00:27,3.069337e-09,1.000000e+02,36.130001,NaN,NaN,-0.000008,0.000044,NaN,NaN,NaN,0.000036,NaN,NaN,3.630255e-10,NaN
0 days 00:00:36,3.069337e-09,1.000000e+02,NaN,NaN,NaN,-0.000008,0.000044,-0.000002,NaN,NaN,0.000036,7.28,NaN,3.630255e-10,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0 days 14:21:42,1.000000e+01,2.482298e-08,NaN,NaN,NaN,2430.999928,2188.030014,52.720001,NaN,NaN,3599.999969,6.44,NaN,5.000000e-02,NaN
0 days 14:21:44,3.069337e-09,2.482298e-08,NaN,NaN,NaN,2430.999928,2188.030014,NaN,NaN,NaN,3599.999969,NaN,NaN,5.000000e-02,NaN
0 days 14:21:53,3.069337e-09,2.482298e-08,NaN,NaN,NaN,2430.999928,2188.030014,52.950001,NaN,NaN,3599.999969,6.44,NaN,5.000000e-02,NaN
0 days 14:22:04,3.069337e-09,2.482298e-08,NaN,NaN,NaN,2430.999928,2188.030014,53.240002,NaN,NaN,3599.999969,6.44,NaN,5.000000e-02,NaN
0 days 14:22:07,3.069337e-09,2.482298e-08,NaN,NaN,NaN,2430.999928,2188.030014,NaN,NaN,NaN,3599.999969,NaN,NaN,5.000000e-02,NaN

In [12]:
(data - decoded).abs().max() / (data).abs().mean()

variable
Flow_Air                         4.303819e-10
StirringSpeed                    4.049686e-07
Temperature                      4.189417e-09
Acetate                          3.191738e-08
Base                             3.703277e-08
Cumulated_feed_volume_glucose    1.404406e-07
Cumulated_feed_volume_medium     3.028568e-08
DOT                              4.286896e-08
Glucose                          2.136378e-08
OD600                            7.954899e-08
Probe_Volume                     1.943248e-08
pH                               4.912166e-09
Fluo_GFP                         1.873869e-07
InducerConcentration             2.134869e-08
Volume                                    NaN
dtype: float64

In [13]:
pandas.testing.assert_frame_equal(data, decoded, atol=10e-5)