In [1]:
%config InteractiveShell.ast_node_interactivity='last_expr_or_assign'  # always print last expr.
%config InlineBackend.figure_format = 'svg'
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
import tsdm

In [3]:
ds = tsdm.datasets.KIWI_RUNS()

KIWI_RUNS['timeseries', 'metadata', 'units']

In [5]:
from tsdm.encoders.functional import make_masked_format

In [21]:
ts = ds.timeseries.loc[355,11722]

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2019-04-09 18:32:12,0.0,0.0,36.990002,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:18,0.0,0.0,<NA>,<NA>,<NA>,0.0,0.0,89.660004,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:19,0.0,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,6.86,<NA>,0.0,<NA>
2019-04-09 18:32:21,4.997213,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:22,4.997213,0.0,36.98,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-10 07:42:18,4.997972,1500.0,<NA>,<NA>,<NA>,1944.0,844.0,<NA>,<NA>,<NA>,4600.0,<NA>,<NA>,0.0,<NA>
2019-04-10 07:43:09,4.997972,1500.0,37.02,<NA>,<NA>,1944.0,844.0,<NA>,<NA>,<NA>,4600.0,<NA>,<NA>,0.0,<NA>
2019-04-10 07:43:15,4.997972,1500.0,<NA>,<NA>,<NA>,1944.0,844.0,1.46,<NA>,<NA>,4600.0,<NA>,<NA>,0.0,<NA>
2019-04-10 07:43:16,4.997972,1500.0,<NA>,<NA>,<NA>,1944.0,844.0,<NA>,<NA>,<NA>,4600.0,5.81,<NA>,0.0,<NA>
2019-04-10 07:43:18,4.999511,1500.0,<NA>,<NA>,<NA>,1944.0,844.0,<NA>,<NA>,<NA>,4600.0,<NA>,<NA>,0.0,<NA>

In [19]:
ts = ts.reset_index([0, 1], drop=True)

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2019-04-09 18:32:12,0.0,0.0,36.990002,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:18,0.0,0.0,<NA>,<NA>,<NA>,0.0,0.0,89.660004,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:19,0.0,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,6.86,<NA>,0.0,<NA>
2019-04-09 18:32:21,4.997213,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
2019-04-09 18:32:22,4.997213,0.0,36.98,<NA>,<NA>,0.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,0.0,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-26 22:41:26,5.0,0.0,<NA>,<NA>,<NA>,1061.0,3787.307373,<NA>,<NA>,<NA>,5500.0,<NA>,<NA>,0.0,-312.692749
2021-10-26 22:42:11,5.0,0.0,37.450001,<NA>,<NA>,1061.0,3787.307373,<NA>,<NA>,<NA>,5500.0,<NA>,<NA>,0.0,<NA>
2021-10-26 22:42:20,5.0,0.0,<NA>,<NA>,<NA>,1061.0,3787.307373,79.459999,<NA>,<NA>,5500.0,7.320229,<NA>,0.0,<NA>
2021-10-26 22:43:22,5.0,0.0,37.439999,<NA>,<NA>,1061.0,3787.307373,<NA>,<NA>,<NA>,5500.0,<NA>,<NA>,0.0,<NA>
2021-10-26 22:43:31,5.0,0.0,<NA>,<NA>,<NA>,1061.0,3787.307373,78.860001,<NA>,<NA>,5500.0,7.336412,<NA>,0.0,<NA>

In [24]:
import numpy as np

In [26]:
np.zeros(5, dtype="datetime64[ns]")

array(['1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000', '1970-01-01T00:00:00.000000000',
       '1970-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

In [27]:
x, m, d = make_masked_format(ts)

In [29]:
d

variable,Flow_Air,StirringSpeed,Temperature,Acetate,Base,Cumulated_feed_volume_glucose,Cumulated_feed_volume_medium,DOT,Glucose,OD600,Probe_Volume,pH,Fluo_GFP,InducerConcentration,Volume
measurement_time,,,,,,,,,,,,,,,
2019-04-09 18:32:12,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00,0 days 00:00:00
2019-04-09 18:32:18,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06
2019-04-09 18:32:19,0 days 00:00:01,0 days 00:00:01,0 days 00:00:07,0 days 00:00:07,0 days 00:00:07,0 days 00:00:01,0 days 00:00:01,0 days 00:00:01,0 days 00:00:07,0 days 00:00:07,0 days 00:00:01,0 days 00:00:07,0 days 00:00:07,0 days 00:00:01,0 days 00:00:07
2019-04-09 18:32:21,0 days 00:00:02,0 days 00:00:02,0 days 00:00:09,0 days 00:00:09,0 days 00:00:09,0 days 00:00:02,0 days 00:00:02,0 days 00:00:03,0 days 00:00:09,0 days 00:00:09,0 days 00:00:02,0 days 00:00:02,0 days 00:00:09,0 days 00:00:02,0 days 00:00:09
2019-04-09 18:32:22,0 days 00:00:01,0 days 00:00:01,0 days 00:00:10,0 days 00:00:10,0 days 00:00:10,0 days 00:00:01,0 days 00:00:01,0 days 00:00:04,0 days 00:00:10,0 days 00:00:10,0 days 00:00:01,0 days 00:00:03,0 days 00:00:10,0 days 00:00:01,0 days 00:00:10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-10 07:42:18,0 days 00:00:02,0 days 00:00:02,0 days 00:00:09,0 days 04:42:51,0 days 00:27:25,0 days 00:00:02,0 days 00:00:02,0 days 00:00:03,0 days 00:14:14,0 days 00:14:14,0 days 00:00:02,0 days 00:00:02,0 days 13:10:06,0 days 00:00:02,0 days 13:10:06
2019-04-10 07:43:09,0 days 00:00:51,0 days 00:00:51,0 days 00:01:00,0 days 04:43:42,0 days 00:28:16,0 days 00:00:51,0 days 00:00:51,0 days 00:00:54,0 days 00:15:05,0 days 00:15:05,0 days 00:00:51,0 days 00:00:53,0 days 13:10:57,0 days 00:00:51,0 days 13:10:57
2019-04-10 07:43:15,0 days 00:00:06,0 days 00:00:06,0 days 00:00:06,0 days 04:43:48,0 days 00:28:22,0 days 00:00:06,0 days 00:00:06,0 days 00:01:00,0 days 00:15:11,0 days 00:15:11,0 days 00:00:06,0 days 00:00:59,0 days 13:11:03,0 days 00:00:06,0 days 13:11:03
2019-04-10 07:43:16,0 days 00:00:01,0 days 00:00:01,0 days 00:00:07,0 days 04:43:49,0 days 00:28:23,0 days 00:00:01,0 days 00:00:01,0 days 00:00:01,0 days 00:15:12,0 days 00:15:12,0 days 00:00:01,0 days 00:01:00,0 days 13:11:04,0 days 00:00:01,0 days 13:11:04
2019-04-10 07:43:18,0 days 00:00:02,0 days 00:00:02,0 days 00:00:09,0 days 04:43:51,0 days 00:28:25,0 days 00:00:02,0 days 00:00:02,0 days 00:00:03,0 days 00:15:14,0 days 00:15:14,0 days 00:00:02,0 days 00:00:02,0 days 13:11:06,0 days 00:00:02,0 days 13:11:06

variable                                  Flow_Air  StirringSpeed  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       0.0            0.0
                     2019-04-09 18:32:18       0.0            0.0
                     2019-04-09 18:32:19       0.0            0.0
                     2019-04-09 18:32:21  4.997213            0.0
                     2019-04-09 18:32:22  4.997213            0.0
...                                            ...            ...
510    16871         2021-10-26 22:41:26       5.0            0.0
                     2021-10-26 22:42:11       5.0            0.0
                     2021-10-26 22:42:20       5.0            0.0
                     2021-10-26 22:43:22       5.0            0.0
                     2021-10-26 22:43:31       5.0            0.0

variable                                  Temperature  Acetate  Base  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12    36.990002     <NA>  <NA>
                     2019-04-09 18:32:18         <NA>     <NA>  <NA>
                     2019-04-09 18:32:19         <NA>     <NA>  <NA>
                     2019-04-09 18:32:21         <NA>     <NA>  <NA>
                     2019-04-09 18:32:22        36.98     <NA>  <NA>
...                                               ...      ...   ...
510    16871         2021-10-26 22:41:26         <NA>     <NA>  <NA>
                     2021-10-26 22:42:11    37.450001     <NA>  <NA>
                     2021-10-26 22:42:20         <NA>     <NA>  <NA>
                     2021-10-26 22:43:22    37.439999     <NA>  <NA>
                     2021-10-26 22:43:31         <NA>     <NA>  <NA>

variable                                  Cumulated_feed_volume_glucose  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                            0.0
                     2019-04-09 18:32:18                            0.0
                     2019-04-09 18:32:19                            0.0
                     2019-04-09 18:32:21                            0.0
                     2019-04-09 18:32:22                            0.0
...                                                                 ...
510    16871         2021-10-26 22:41:26                         1061.0
                     2021-10-26 22:42:11                         1061.0
                     2021-10-26 22:42:20                         1061.0
                     2021-10-26 22:43:22                         1061.0
                     2021-10-26 22:43:31                         1061.0

variable                                  Cumulated_feed_volume_medium  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                           0.0
                     2019-04-09 18:32:18                           0.0
                     2019-04-09 18:32:19                           0.0
                     2019-04-09 18:32:21                           0.0
                     2019-04-09 18:32:22                           0.0
...                                                                ...
510    16871         2021-10-26 22:41:26                   3787.307373
                     2021-10-26 22:42:11                   3787.307373
                     2021-10-26 22:42:20                   3787.307373
                     2021-10-26 22:43:22                   3787.307373
                     2021-10-26 22:43:31                   3787.307373

variable                                        DOT  Glucose  OD600  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12       <NA>     <NA>   <NA>
                     2019-04-09 18:32:18  89.660004     <NA>   <NA>
                     2019-04-09 18:32:19       <NA>     <NA>   <NA>
                     2019-04-09 18:32:21       <NA>     <NA>   <NA>
                     2019-04-09 18:32:22       <NA>     <NA>   <NA>
...                                             ...      ...    ...
510    16871         2021-10-26 22:41:26       <NA>     <NA>   <NA>
                     2021-10-26 22:42:11       <NA>     <NA>   <NA>
                     2021-10-26 22:42:20  79.459999     <NA>   <NA>
                     2021-10-26 22:43:22       <NA>     <NA>   <NA>
                     2021-10-26 22:43:31  78.860001     <NA>   <NA>

variable                                  Probe_Volume        pH  Fluo_GFP  \
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12           0.0      <NA>      <NA>
                     2019-04-09 18:32:18           0.0      <NA>      <NA>
                     2019-04-09 18:32:19           0.0      6.86      <NA>
                     2019-04-09 18:32:21           0.0      <NA>      <NA>
                     2019-04-09 18:32:22           0.0      <NA>      <NA>
...                                                ...       ...       ...
510    16871         2021-10-26 22:41:26        5500.0      <NA>      <NA>
                     2021-10-26 22:42:11        5500.0      <NA>      <NA>
                     2021-10-26 22:42:20        5500.0  7.320229      <NA>
                     2021-10-26 22:43:22        5500.0      <NA>      <NA>
                     2021-10-26 22:43:31        5500.0  7.336412      <NA>

variable                                  InducerConcentration      Volume
run_id experiment_id measurement_time
355    11722         2019-04-09 18:32:12                   0.0        <NA>
                     2019-04-09 18:32:18                   0.0        <NA>
                     2019-04-09 18:32:19                   0.0        <NA>
                     2019-04-09 18:32:21                   0.0        <NA>
                     2019-04-09 18:32:22                   0.0        <NA>
...                                                        ...         ...
510    16871         2021-10-26 22:41:26                   0.0 -312.692749
                     2021-10-26 22:42:11                   0.0        <NA>
                     2021-10-26 22:42:20                   0.0        <NA>
                     2021-10-26 22:43:22                   0.0        <NA>
                     2021-10-26 22:43:31                   0.0        <NA>

[441907 rows x 15 columns]